# -*- coding: utf-8 -*- 
import Pylatte.WebServer.formFile as formFile
class tutorial:
	pylToHtmlResult=""
	sessionDic=dict()
	def __init__(self,param,pyFile,session,headerInfo,lattedb):
		self.generate(param,pyFile,session,headerInfo,lattedb)

	def generate(self,param,pyFile,session,headerInfo,lattedb):
		self.pylToHtmlResult+=str("""<!DOCTYPE html>""")
		self.pylToHtmlResult+=str("""
<html>""")
		self.pylToHtmlResult+=str("""
	<head>""")
		self.pylToHtmlResult+=str("""
	<meta name="viewport" content="width=device-width, initial-scale=1">""")
		self.pylToHtmlResult+=str("""
	<meta http-equiv="Content-Type" content="text/html; charset=UTF-8">""")
		self.pylToHtmlResult+=str("""
	<title>""")
		self.pylToHtmlResult+=str("""Pylatte""")
		self.pylToHtmlResult+=str(""" -""")
		self.pylToHtmlResult+=str(""" Web""")
		self.pylToHtmlResult+=str(""" framework""")
		self.pylToHtmlResult+=str(""" based""")
		self.pylToHtmlResult+=str(""" on""")
		self.pylToHtmlResult+=str(""" Python3""")
		self.pylToHtmlResult+=str("""</title>""")
		self.pylToHtmlResult+=str("""
	
	<!-- favicon -->""")
		self.pylToHtmlResult+=str("""
	<link rel="shortcut icon" href="../pyl/favicon.ico" type="image/x-icon">""")
		self.pylToHtmlResult+=str("""
	<link rel="icon" href="../pyl/favicon.ico" type="image/x-icon">""")
		self.pylToHtmlResult+=str("""

	<!-- Include required JS files -->""")
		self.pylToHtmlResult+=str("""
	<script type="text/javascript" src="../pyl/syntaxhighlighter/js/xregexp.js">""")
		self.pylToHtmlResult+=str("""</script>""")
		self.pylToHtmlResult+=str("""
	<script type="text/javascript" src="../pyl/syntaxhighlighter/js/shCore.js">""")
		self.pylToHtmlResult+=str("""</script>""")
		self.pylToHtmlResult+=str("""
	 
	<!--
	    At least one brush, here we choose JS. You need to include a brush for every
	    language you want to highlight
	-->""")
		self.pylToHtmlResult+=str("""
	<script type="text/javascript" src="../pyl/syntaxhighlighter/lang/shBrushXml.js">""")
		self.pylToHtmlResult+=str("""</script>""")
		self.pylToHtmlResult+=str("""
	<script type="text/javascript" src="../pyl/syntaxhighlighter/lang/shBrushBash.js">""")
		self.pylToHtmlResult+=str("""</script>""")
		self.pylToHtmlResult+=str("""
	 
	<!-- Include *at least* the core style and default theme -->""")
		self.pylToHtmlResult+=str("""
	<link href="../pyl/syntaxhighlighter/css/shCore.css" rel="stylesheet" type="text/css" />""")
		self.pylToHtmlResult+=str("""
	<link href="../pyl/syntaxhighlighter/css/shThemeDefault.css" rel="stylesheet" type="text/css" />""")
		self.pylToHtmlResult+=str("""
	
	
	
	<link rel="stylesheet"  href="../pyl/css/jquery.mobile-1.2.0.css"/>""")
		self.pylToHtmlResult+=str("""
	<link rel="stylesheet"  href="../pyl/css/jqm-docs.css"/>""")
		self.pylToHtmlResult+=str("""
	
	<script src="../pyl/js/jquery.js">""")
		self.pylToHtmlResult+=str("""</script>""")
		self.pylToHtmlResult+=str("""
	<script src="../pyl/js/jqm-docs.js">""")
		self.pylToHtmlResult+=str("""</script>""")
		self.pylToHtmlResult+=str("""
	<script src="../pyl/js/jquery.mobile.themeswitcher.js">""")
		self.pylToHtmlResult+=str("""</script>""")
		self.pylToHtmlResult+=str("""
	<script src="../pyl/js/jquery.mobile-1.2.0.min.js">""")
		self.pylToHtmlResult+=str("""</script>""")
		self.pylToHtmlResult+=str("""
	
	<script type="text/javascript">""")
		self.pylToHtmlResult+=str("""

	  var""")
		self.pylToHtmlResult+=str(""" _gaq""")
		self.pylToHtmlResult+=str(""" =""")
		self.pylToHtmlResult+=str(""" _gaq""")
		self.pylToHtmlResult+=str(""" ||""")
		self.pylToHtmlResult+=str(""" [];""")
		self.pylToHtmlResult+=str("""
	  _gaq.push(['_setAccount',""")
		self.pylToHtmlResult+=str(""" 'UA-26668199-1']);""")
		self.pylToHtmlResult+=str("""
	  _gaq.push(['_trackPageview']);""")
		self.pylToHtmlResult+=str("""
	
	  (function()""")
		self.pylToHtmlResult+=str(""" {""")
		self.pylToHtmlResult+=str("""
	    var""")
		self.pylToHtmlResult+=str(""" ga""")
		self.pylToHtmlResult+=str(""" =""")
		self.pylToHtmlResult+=str(""" document.createElement('script');""")
		self.pylToHtmlResult+=str(""" ga.type""")
		self.pylToHtmlResult+=str(""" =""")
		self.pylToHtmlResult+=str(""" 'text/javascript';""")
		self.pylToHtmlResult+=str(""" ga.async""")
		self.pylToHtmlResult+=str(""" =""")
		self.pylToHtmlResult+=str(""" true;""")
		self.pylToHtmlResult+=str("""
	    ga.src""")
		self.pylToHtmlResult+=str(""" =""")
		self.pylToHtmlResult+=str(""" ('https:'""")
		self.pylToHtmlResult+=str(""" ==""")
		self.pylToHtmlResult+=str(""" document.location.protocol""")
		self.pylToHtmlResult+=str(""" ?""")
		self.pylToHtmlResult+=str(""" 'https://ssl'""")
		self.pylToHtmlResult+=str(""" :""")
		self.pylToHtmlResult+=str(""" 'http://www')""")
		self.pylToHtmlResult+=str(""" +""")
		self.pylToHtmlResult+=str(""" '.google-analytics.com/ga.js';""")
		self.pylToHtmlResult+=str("""
	    var""")
		self.pylToHtmlResult+=str(""" s""")
		self.pylToHtmlResult+=str(""" =""")
		self.pylToHtmlResult+=str(""" document.getElementsByTagName('script')[0];""")
		self.pylToHtmlResult+=str(""" s.parentNode.insertBefore(ga,""")
		self.pylToHtmlResult+=str(""" s);""")
		self.pylToHtmlResult+=str("""
	  })();""")
		self.pylToHtmlResult+=str("""
	
	</script>""")
		self.pylToHtmlResult+=str("""
	
	</head>""")
		self.pylToHtmlResult+=str("""

<body>""")
		self.pylToHtmlResult+=str("""
	<div data-role="page" class="type-interior">""")
		self.pylToHtmlResult+=str("""

		<div data-role="header" data-theme="b">""")
		self.pylToHtmlResult+=str("""
		<h1>""")
		self.pylToHtmlResult+=str("""Pylatte""")
		self.pylToHtmlResult+=str(""" Official""")
		self.pylToHtmlResult+=str(""" Webpage""")
		self.pylToHtmlResult+=str("""</h1>""")
		self.pylToHtmlResult+=str("""
		<a href="../../" target="_self" data-icon="home" data-iconpos="notext" data-direction="reverse" class="ui-btn-right jqm-home">""")
		self.pylToHtmlResult+=str("""Home""")
		self.pylToHtmlResult+=str("""</a>""")
		self.pylToHtmlResult+=str("""
	</div>""")
		self.pylToHtmlResult+=str("""<!-- /header -->""")
		self.pylToHtmlResult+=str("""

	<div data-role="content">""")
		self.pylToHtmlResult+=str("""
			<div class="content-primary">""")
		self.pylToHtmlResult+=str("""
			<h1>""")
		self.pylToHtmlResult+=str("""Tutorial""")
		self.pylToHtmlResult+=str("""</h1>""")
		self.pylToHtmlResult+=str("""
				
			<h2>""")
		self.pylToHtmlResult+=str("""Hello""")
		self.pylToHtmlResult+=str(""" Pylatte""")
		self.pylToHtmlResult+=str("""</h2>""")
		self.pylToHtmlResult+=str("""
				<p>""")
		self.pylToHtmlResult+=str("""Let's""")
		self.pylToHtmlResult+=str(""" print""")
		self.pylToHtmlResult+=str(""" <i>""")
		self.pylToHtmlResult+=str("""Hello""")
		self.pylToHtmlResult+=str(""" Pylatte""")
		self.pylToHtmlResult+=str("""</i>""")
		self.pylToHtmlResult+=str("""on""")
		self.pylToHtmlResult+=str(""" pylatte""")
		self.pylToHtmlResult+=str(""" tutorial""")
		self.pylToHtmlResult+=str(""" as""")
		self.pylToHtmlResult+=str(""" a""")
		self.pylToHtmlResult+=str(""" first""")
		self.pylToHtmlResult+=str(""" step.""")
		self.pylToHtmlResult+=str(""" First""")
		self.pylToHtmlResult+=str(""" of""")
		self.pylToHtmlResult+=str(""" all,""")
		self.pylToHtmlResult+=str(""" open""")
		self.pylToHtmlResult+=str(""" a""")
		self.pylToHtmlResult+=str(""" text""")
		self.pylToHtmlResult+=str(""" editor,""")
		self.pylToHtmlResult+=str(""" and""")
		self.pylToHtmlResult+=str(""" it""")
		self.pylToHtmlResult+=str(""" will""")
		self.pylToHtmlResult+=str(""" be""")
		self.pylToHtmlResult+=str(""" saved""")
		self.pylToHtmlResult+=str(""" as""")
		self.pylToHtmlResult+=str(""" <i>""")
		self.pylToHtmlResult+=str("""hellopy.""")
		self.pylToHtmlResult+=str("""<b>""")
		self.pylToHtmlResult+=str("""pyl""")
		self.pylToHtmlResult+=str("""</b>""")
		self.pylToHtmlResult+=str("""</i>""")
		self.pylToHtmlResult+=str("""</p>""")
		self.pylToHtmlResult+=str("""
				<p>""")
		self.pylToHtmlResult+=str("""You""")
		self.pylToHtmlResult+=str(""" can""")
		self.pylToHtmlResult+=str(""" use""")
		self.pylToHtmlResult+=str(""" python""")
		self.pylToHtmlResult+=str(""" code""")
		self.pylToHtmlResult+=str(""" in""")
		self.pylToHtmlResult+=str(""" pyl""")
		self.pylToHtmlResult+=str(""" file""")
		self.pylToHtmlResult+=str(""" format""")
		self.pylToHtmlResult+=str(""" on""")
		self.pylToHtmlResult+=str(""" pylatte.""")
		self.pylToHtmlResult+=str(""" pyl""")
		self.pylToHtmlResult+=str(""" consists""")
		self.pylToHtmlResult+=str(""" of""")
		self.pylToHtmlResult+=str(""" HTML""")
		self.pylToHtmlResult+=str(""" and""")
		self.pylToHtmlResult+=str(""" python.""")
		self.pylToHtmlResult+=str("""</p>""")
		self.pylToHtmlResult+=str("""
				<p>""")
		self.pylToHtmlResult+=str("""To""")
		self.pylToHtmlResult+=str(""" make""")
		self.pylToHtmlResult+=str(""" pyl""")
		self.pylToHtmlResult+=str(""" page""")
		self.pylToHtmlResult+=str(""" working""")
		self.pylToHtmlResult+=str(""" on""")
		self.pylToHtmlResult+=str(""" pylatte,""")
		self.pylToHtmlResult+=str(""" wrap""")
		self.pylToHtmlResult+=str(""" python""")
		self.pylToHtmlResult+=str(""" code""")
		self.pylToHtmlResult+=str(""" with""")
		self.pylToHtmlResult+=str(""" <b>""")
		self.pylToHtmlResult+=str("""&lt;$""")
		self.pylToHtmlResult+=str("""</b>""")
		self.pylToHtmlResult+=str(""" and""")
		self.pylToHtmlResult+=str(""" <b>""")
		self.pylToHtmlResult+=str("""$&gt;""")
		self.pylToHtmlResult+=str("""</b>""")
		self.pylToHtmlResult+=str(""".""")
		self.pylToHtmlResult+=str(""" And""")
		self.pylToHtmlResult+=str(""" if""")
		self.pylToHtmlResult+=str(""" you""")
		self.pylToHtmlResult+=str(""" put""")
		self.pylToHtmlResult+=str(""" your""")
		self.pylToHtmlResult+=str(""" <i>""")
		self.pylToHtmlResult+=str("""variable""")
		self.pylToHtmlResult+=str("""</i>""")
		self.pylToHtmlResult+=str(""" between""")
		self.pylToHtmlResult+=str(""" <b>""")
		self.pylToHtmlResult+=str("""&lt;$=""")
		self.pylToHtmlResult+=str("""</b>""")
		self.pylToHtmlResult+=str(""" and""")
		self.pylToHtmlResult+=str(""" <b>""")
		self.pylToHtmlResult+=str("""$&gt;""")
		self.pylToHtmlResult+=str("""</b>""")
		self.pylToHtmlResult+=str(""" such""")
		self.pylToHtmlResult+=str(""" as""")
		self.pylToHtmlResult+=str(""" <b>""")
		self.pylToHtmlResult+=str("""&lt;$=""")
		self.pylToHtmlResult+=str("""</b>""")
		self.pylToHtmlResult+=str("""<i>""")
		self.pylToHtmlResult+=str("""variable""")
		self.pylToHtmlResult+=str("""</i>""")
		self.pylToHtmlResult+=str("""<b>""")
		self.pylToHtmlResult+=str("""$&gt;""")
		self.pylToHtmlResult+=str("""</b>""")
		self.pylToHtmlResult+=str(""",""")
		self.pylToHtmlResult+=str(""" the""")
		self.pylToHtmlResult+=str(""" <i>""")
		self.pylToHtmlResult+=str("""variable""")
		self.pylToHtmlResult+=str("""</i>""")
		self.pylToHtmlResult+=str(""" will""")
		self.pylToHtmlResult+=str(""" be""")
		self.pylToHtmlResult+=str(""" automatically""")
		self.pylToHtmlResult+=str(""" printed""")
		self.pylToHtmlResult+=str(""" on""")
		self.pylToHtmlResult+=str(""" the""")
		self.pylToHtmlResult+=str(""" web""")
		self.pylToHtmlResult+=str(""" page""")
		self.pylToHtmlResult+=str(""" by""")
		self.pylToHtmlResult+=str(""" pylatte""")
		self.pylToHtmlResult+=str(""" translation""")
		self.pylToHtmlResult+=str(""" module.""")
		self.pylToHtmlResult+=str(""" </p>""")
		self.pylToHtmlResult+=str("""
				<p>""")
		self.pylToHtmlResult+=str("""Caution""")
		self.pylToHtmlResult+=str(""" :""")
		self.pylToHtmlResult+=str(""" If""")
		self.pylToHtmlResult+=str(""" you""")
		self.pylToHtmlResult+=str(""" use""")
		self.pylToHtmlResult+=str(""" <b>""")
		self.pylToHtmlResult+=str("""print()""")
		self.pylToHtmlResult+=str("""</b>""")
		self.pylToHtmlResult+=str(""" function,""")
		self.pylToHtmlResult+=str(""" it""")
		self.pylToHtmlResult+=str(""" will""")
		self.pylToHtmlResult+=str(""" be""")
		self.pylToHtmlResult+=str(""" printed""")
		self.pylToHtmlResult+=str(""" on""")
		self.pylToHtmlResult+=str(""" web""")
		self.pylToHtmlResult+=str(""" server""")
		self.pylToHtmlResult+=str(""" console.""")
		self.pylToHtmlResult+=str("""</p>""")
		self.pylToHtmlResult+=str("""
			
				<pre class="brush: xml">""")
		self.pylToHtmlResult+=str("""
				&lt;$""")
		self.pylToHtmlResult+=str("""
				hi=&quot;hello""")
		self.pylToHtmlResult+=str(""" pylatte&quot;""")
		self.pylToHtmlResult+=str("""
				$&gt;""")
		self.pylToHtmlResult+=str("""
				<h1>""")
		self.pylToHtmlResult+=str("""&lt;$=hi$&gt;""")
		self.pylToHtmlResult+=str("""</h1>""")
		self.pylToHtmlResult+=str("""
				</pre>""")
		self.pylToHtmlResult+=str("""
				<p>""")
		self.pylToHtmlResult+=str("""In""")
		self.pylToHtmlResult+=str(""" python""")
		self.pylToHtmlResult+=str(""" language,""")
		self.pylToHtmlResult+=str(""" indentation""")
		self.pylToHtmlResult+=str(""" is""")
		self.pylToHtmlResult+=str(""" absolutely""")
		self.pylToHtmlResult+=str(""" important.""")
		self.pylToHtmlResult+=str(""" So""")
		self.pylToHtmlResult+=str(""" we""")
		self.pylToHtmlResult+=str(""" strongly""")
		self.pylToHtmlResult+=str(""" recommend""")
		self.pylToHtmlResult+=str(""" to""")
		self.pylToHtmlResult+=str(""" use""")
		self.pylToHtmlResult+=str(""" python""")
		self.pylToHtmlResult+=str(""" code""")
		self.pylToHtmlResult+=str(""" under""")
		self.pylToHtmlResult+=str(""" <b>""")
		self.pylToHtmlResult+=str("""&lt;$""")
		self.pylToHtmlResult+=str("""</b>""")
		self.pylToHtmlResult+=str(""",""")
		self.pylToHtmlResult+=str(""" and""")
		self.pylToHtmlResult+=str(""" type""")
		self.pylToHtmlResult+=str(""" <b>""")
		self.pylToHtmlResult+=str("""$&gt;""")
		self.pylToHtmlResult+=str("""</b>""")
		self.pylToHtmlResult+=str(""" on""")
		self.pylToHtmlResult+=str(""" new""")
		self.pylToHtmlResult+=str(""" line""")
		self.pylToHtmlResult+=str(""" after""")
		self.pylToHtmlResult+=str(""" python""")
		self.pylToHtmlResult+=str(""" code.""")
		self.pylToHtmlResult+=str(""" Refer""")
		self.pylToHtmlResult+=str(""" to""")
		self.pylToHtmlResult+=str(""" the""")
		self.pylToHtmlResult+=str(""" following""")
		self.pylToHtmlResult+=str(""" code.""")
		self.pylToHtmlResult+=str("""</p>""")
		self.pylToHtmlResult+=str("""
				<p>""")
		self.pylToHtmlResult+=str("""Type""")
		self.pylToHtmlResult+=str(""" the""")
		self.pylToHtmlResult+=str(""" code""")
		self.pylToHtmlResult+=str(""" in""")
		self.pylToHtmlResult+=str(""" hellopy.pyl""")
		self.pylToHtmlResult+=str(""" and""")
		self.pylToHtmlResult+=str(""" save""")
		self.pylToHtmlResult+=str(""" it""")
		self.pylToHtmlResult+=str(""" again.""")
		self.pylToHtmlResult+=str(""" After""")
		self.pylToHtmlResult+=str(""" running""")
		self.pylToHtmlResult+=str(""" pylatte""")
		self.pylToHtmlResult+=str(""" web""")
		self.pylToHtmlResult+=str(""" server,""")
		self.pylToHtmlResult+=str(""" you""")
		self.pylToHtmlResult+=str(""" can""")
		self.pylToHtmlResult+=str(""" see""")
		self.pylToHtmlResult+=str(""" <b>""")
		self.pylToHtmlResult+=str("""hello""")
		self.pylToHtmlResult+=str(""" pylatte""")
		self.pylToHtmlResult+=str("""</b>""")
		self.pylToHtmlResult+=str(""".""")
		self.pylToHtmlResult+=str("""
			
			<h2>""")
		self.pylToHtmlResult+=str("""Starting""")
		self.pylToHtmlResult+=str(""" pylatte""")
		self.pylToHtmlResult+=str(""" web""")
		self.pylToHtmlResult+=str(""" server""")
		self.pylToHtmlResult+=str("""</h2>""")
		self.pylToHtmlResult+=str("""
				<p>""")
		self.pylToHtmlResult+=str("""Basically,""")
		self.pylToHtmlResult+=str(""" default""")
		self.pylToHtmlResult+=str(""" port""")
		self.pylToHtmlResult+=str(""" number""")
		self.pylToHtmlResult+=str(""" is""")
		self.pylToHtmlResult+=str(""" 80""")
		self.pylToHtmlResult+=str(""" on""")
		self.pylToHtmlResult+=str(""" HTTP.""")
		self.pylToHtmlResult+=str(""" If""")
		self.pylToHtmlResult+=str(""" you""")
		self.pylToHtmlResult+=str(""" want,""")
		self.pylToHtmlResult+=str(""" you""")
		self.pylToHtmlResult+=str(""" can""")
		self.pylToHtmlResult+=str(""" change""")
		self.pylToHtmlResult+=str(""" port""")
		self.pylToHtmlResult+=str(""" number""")
		self.pylToHtmlResult+=str(""" in""")
		self.pylToHtmlResult+=str(""" <i>""")
		self.pylToHtmlResult+=str("""pylatte_config.xml""")
		self.pylToHtmlResult+=str("""</i>""")
		self.pylToHtmlResult+=str("""</p>""")
		self.pylToHtmlResult+=str("""
				<pre class="brush: xml">""")
		self.pylToHtmlResult+=str("""
					<pylatte-server>""")
		self.pylToHtmlResult+=str("""
						<port>""")
		self.pylToHtmlResult+=str("""80""")
		self.pylToHtmlResult+=str("""</port>""")
		self.pylToHtmlResult+=str("""
					</pylatte-server>""")
		self.pylToHtmlResult+=str("""
				</pre>""")
		self.pylToHtmlResult+=str("""
				<p>""")
		self.pylToHtmlResult+=str("""There""")
		self.pylToHtmlResult+=str(""" are""")
		self.pylToHtmlResult+=str(""" many""")
		self.pylToHtmlResult+=str(""" options""")
		self.pylToHtmlResult+=str(""" in""")
		self.pylToHtmlResult+=str(""" <i>""")
		self.pylToHtmlResult+=str("""pylatte_config.xml""")
		self.pylToHtmlResult+=str("""</i>""")
		self.pylToHtmlResult+=str(""".""")
		self.pylToHtmlResult+=str(""" To""")
		self.pylToHtmlResult+=str(""" change""")
		self.pylToHtmlResult+=str(""" port""")
		self.pylToHtmlResult+=str(""" number,""")
		self.pylToHtmlResult+=str(""" we""")
		self.pylToHtmlResult+=str(""" need""")
		self.pylToHtmlResult+=str(""" to""")
		self.pylToHtmlResult+=str(""" focus""")
		self.pylToHtmlResult+=str(""" on""")
		self.pylToHtmlResult+=str(""" only""")
		self.pylToHtmlResult+=str(""" &lt;pylatte-server&gt;""")
		self.pylToHtmlResult+=str(""" tag.""")
		self.pylToHtmlResult+=str(""" Modify""")
		self.pylToHtmlResult+=str(""" the""")
		self.pylToHtmlResult+=str(""" value""")
		self.pylToHtmlResult+=str(""" of""")
		self.pylToHtmlResult+=str(""" &lt;port&gt;""")
		self.pylToHtmlResult+=str(""" tag""")
		self.pylToHtmlResult+=str(""" from""")
		self.pylToHtmlResult+=str(""" default""")
		self.pylToHtmlResult+=str(""" port(80)""")
		self.pylToHtmlResult+=str(""" to""")
		self.pylToHtmlResult+=str(""" what""")
		self.pylToHtmlResult+=str(""" you""")
		self.pylToHtmlResult+=str(""" want(e.g.""")
		self.pylToHtmlResult+=str(""" 8000).""")
		self.pylToHtmlResult+=str("""</p>""")
		self.pylToHtmlResult+=str("""
				<p>""")
		self.pylToHtmlResult+=str("""Caution""")
		self.pylToHtmlResult+=str(""" :""")
		self.pylToHtmlResult+=str(""" You""")
		self.pylToHtmlResult+=str(""" have""")
		self.pylToHtmlResult+=str(""" to""")
		self.pylToHtmlResult+=str(""" check""")
		self.pylToHtmlResult+=str(""" if""")
		self.pylToHtmlResult+=str(""" the""")
		self.pylToHtmlResult+=str(""" port""")
		self.pylToHtmlResult+=str(""" number""")
		self.pylToHtmlResult+=str(""" is""")
		self.pylToHtmlResult+=str(""" being""")
		self.pylToHtmlResult+=str(""" used""")
		self.pylToHtmlResult+=str(""" by""")
		self.pylToHtmlResult+=str(""" another""")
		self.pylToHtmlResult+=str(""" program""")
		self.pylToHtmlResult+=str(""" before""")
		self.pylToHtmlResult+=str(""" you""")
		self.pylToHtmlResult+=str(""" change.""")
		self.pylToHtmlResult+=str("""</p>""")
		self.pylToHtmlResult+=str("""
				
				<p>""")
		self.pylToHtmlResult+=str("""To""")
		self.pylToHtmlResult+=str(""" start""")
		self.pylToHtmlResult+=str(""" pylatte""")
		self.pylToHtmlResult+=str(""" web""")
		self.pylToHtmlResult+=str(""" server,""")
		self.pylToHtmlResult+=str(""" move""")
		self.pylToHtmlResult+=str(""" to""")
		self.pylToHtmlResult+=str(""" appropriate""")
		self.pylToHtmlResult+=str(""" path""")
		self.pylToHtmlResult+=str(""" where""")
		self.pylToHtmlResult+=str(""" pylatte""")
		self.pylToHtmlResult+=str(""" is""")
		self.pylToHtmlResult+=str(""" installed""")
		self.pylToHtmlResult+=str(""" and""")
		self.pylToHtmlResult+=str(""" run""")
		self.pylToHtmlResult+=str(""" following""")
		self.pylToHtmlResult+=str(""" command""")
		self.pylToHtmlResult+=str(""" into""")
		self.pylToHtmlResult+=str(""" terminal.""")
		self.pylToHtmlResult+=str(""" If""")
		self.pylToHtmlResult+=str(""" operating""")
		self.pylToHtmlResult+=str(""" system""")
		self.pylToHtmlResult+=str(""" is""")
		self.pylToHtmlResult+=str(""" Windows,""")
		self.pylToHtmlResult+=str(""" just""")
		self.pylToHtmlResult+=str(""" execute""")
		self.pylToHtmlResult+=str(""" the""")
		self.pylToHtmlResult+=str(""" latteServerStart.py""")
		self.pylToHtmlResult+=str(""" file.""")
		self.pylToHtmlResult+=str("""</p>""")
		self.pylToHtmlResult+=str("""
				<pre class="brush: bash">""")
		self.pylToHtmlResult+=str("""
					sudo""")
		self.pylToHtmlResult+=str(""" python3""")
		self.pylToHtmlResult+=str(""" latteServerStart.py""")
		self.pylToHtmlResult+=str("""
				</pre>""")
		self.pylToHtmlResult+=str("""
				<p>""")
		self.pylToHtmlResult+=str("""There""")
		self.pylToHtmlResult+=str(""" are""")
		self.pylToHtmlResult+=str(""" just""")
		self.pylToHtmlResult+=str(""" one""")
		self.pylToHtmlResult+=str(""" more""")
		self.pylToHtmlResult+=str(""" step""")
		self.pylToHtmlResult+=str(""" to""")
		self.pylToHtmlResult+=str(""" see""")
		self.pylToHtmlResult+=str(""" <b>""")
		self.pylToHtmlResult+=str("""hello""")
		self.pylToHtmlResult+=str(""" pylatte""")
		self.pylToHtmlResult+=str("""</b>""")
		self.pylToHtmlResult+=str(""".""")
		self.pylToHtmlResult+=str(""" Take""")
		self.pylToHtmlResult+=str(""" URL""")
		self.pylToHtmlResult+=str(""" Mapping""")
		self.pylToHtmlResult+=str(""" below.""")
		self.pylToHtmlResult+=str("""</p>""")
		self.pylToHtmlResult+=str("""
				
			<h2>""")
		self.pylToHtmlResult+=str("""URL""")
		self.pylToHtmlResult+=str(""" Mapping""")
		self.pylToHtmlResult+=str("""</h2>""")
		self.pylToHtmlResult+=str("""
				<p>""")
		self.pylToHtmlResult+=str("""To""")
		self.pylToHtmlResult+=str(""" make""")
		self.pylToHtmlResult+=str(""" pylatte""")
		self.pylToHtmlResult+=str(""" security""")
		self.pylToHtmlResult+=str(""" safe,""")
		self.pylToHtmlResult+=str(""" it""")
		self.pylToHtmlResult+=str(""" is""")
		self.pylToHtmlResult+=str(""" neccesary""")
		self.pylToHtmlResult+=str(""" to""")
		self.pylToHtmlResult+=str(""" fix""")
		self.pylToHtmlResult+=str(""" &lt;pylatte&gt;""")
		self.pylToHtmlResult+=str(""" and""")
		self.pylToHtmlResult+=str(""" &lt;pylatte-mapping&gt;""")
		self.pylToHtmlResult+=str(""" tag""")
		self.pylToHtmlResult+=str(""" in""")
		self.pylToHtmlResult+=str(""" <i>""")
		self.pylToHtmlResult+=str("""pylatte_config.xml""")
		self.pylToHtmlResult+=str("""</i>""")
		self.pylToHtmlResult+=str("""</p>""")
		self.pylToHtmlResult+=str("""
				<pre class="brush: xml">""")
		self.pylToHtmlResult+=str("""
					<pylatte>""")
		self.pylToHtmlResult+=str("""
						<pylatte-name>""")
		self.pylToHtmlResult+=str("""hello_pylatte""")
		self.pylToHtmlResult+=str("""</pylatte-name>""")
		self.pylToHtmlResult+=str("""
						<pylatte-pyl>""")
		self.pylToHtmlResult+=str("""hellopy.pyl""")
		self.pylToHtmlResult+=str("""</pylatte-pyl>""")
		self.pylToHtmlResult+=str("""
					</pylatte>""")
		self.pylToHtmlResult+=str("""
					<pylatte-mapping>""")
		self.pylToHtmlResult+=str("""
						<pylatte-name>""")
		self.pylToHtmlResult+=str("""hello_pylatte""")
		self.pylToHtmlResult+=str("""</pylatte-name>""")
		self.pylToHtmlResult+=str("""
						<url-mapping>""")
		self.pylToHtmlResult+=str("""/py""")
		self.pylToHtmlResult+=str("""</url-mapping>""")
		self.pylToHtmlResult+=str("""
					</pylatte-mapping>""")
		self.pylToHtmlResult+=str("""
				</pre>""")
		self.pylToHtmlResult+=str("""
				<p>""")
		self.pylToHtmlResult+=str("""&lt;pylatte-name&gt;""")
		self.pylToHtmlResult+=str(""" value(e.g.""")
		self.pylToHtmlResult+=str(""" hello_pylatte)""")
		self.pylToHtmlResult+=str(""" in""")
		self.pylToHtmlResult+=str(""" &lt;pylatte&gt;""")
		self.pylToHtmlResult+=str(""" and""")
		self.pylToHtmlResult+=str(""" &lt;pylatte-mapping&gt;""")
		self.pylToHtmlResult+=str(""" is""")
		self.pylToHtmlResult+=str(""" just""")
		self.pylToHtmlResult+=str(""" name""")
		self.pylToHtmlResult+=str(""" to""")
		self.pylToHtmlResult+=str(""" identify""")
		self.pylToHtmlResult+=str(""" each""")
		self.pylToHtmlResult+=str(""" mapping""")
		self.pylToHtmlResult+=str(""" information.""")
		self.pylToHtmlResult+=str("""</p>""")
		self.pylToHtmlResult+=str("""
				<p>""")
		self.pylToHtmlResult+=str("""&lt;pylatte-pyl&gt;""")
		self.pylToHtmlResult+=str(""" value(e.g.""")
		self.pylToHtmlResult+=str(""" hellopy.pyl)""")
		self.pylToHtmlResult+=str(""" in""")
		self.pylToHtmlResult+=str(""" &lt;pylatte&gt;""")
		self.pylToHtmlResult+=str(""" is""")
		self.pylToHtmlResult+=str(""" real""")
		self.pylToHtmlResult+=str(""" pyl""")
		self.pylToHtmlResult+=str(""" page""")
		self.pylToHtmlResult+=str(""" we""")
		self.pylToHtmlResult+=str(""" make.""")
		self.pylToHtmlResult+=str(""" it""")
		self.pylToHtmlResult+=str(""" will""")
		self.pylToHtmlResult+=str(""" be""")
		self.pylToHtmlResult+=str(""" accessed""")
		self.pylToHtmlResult+=str(""" by""")
		self.pylToHtmlResult+=str(""" &lt;url-mapping&gt;""")
		self.pylToHtmlResult+=str(""" value""")
		self.pylToHtmlResult+=str(""" in""")
		self.pylToHtmlResult+=str(""" &lt;pylatte-mapping&gt;.""")
		self.pylToHtmlResult+=str(""" Once""")
		self.pylToHtmlResult+=str(""" more,""")
		self.pylToHtmlResult+=str(""" you""")
		self.pylToHtmlResult+=str(""" have""")
		self.pylToHtmlResult+=str(""" to""")
		self.pylToHtmlResult+=str(""" access""")
		self.pylToHtmlResult+=str(""" http://localhost/py,""")
		self.pylToHtmlResult+=str(""" NOT""")
		self.pylToHtmlResult+=str(""" to""")
		self.pylToHtmlResult+=str(""" http://localhost/hellopy.pyl.""")
		self.pylToHtmlResult+=str(""" This""")
		self.pylToHtmlResult+=str(""" can""")
		self.pylToHtmlResult+=str(""" hide""")
		self.pylToHtmlResult+=str(""" original""")
		self.pylToHtmlResult+=str(""" url,""")
		self.pylToHtmlResult+=str(""" so""")
		self.pylToHtmlResult+=str(""" we""")
		self.pylToHtmlResult+=str(""" think""")
		self.pylToHtmlResult+=str(""" it""")
		self.pylToHtmlResult+=str(""" would""")
		self.pylToHtmlResult+=str(""" make""")
		self.pylToHtmlResult+=str(""" pylatte""")
		self.pylToHtmlResult+=str(""" securtiy""")
		self.pylToHtmlResult+=str(""" much""")
		self.pylToHtmlResult+=str(""" higher.""")
		self.pylToHtmlResult+=str("""</p>""")
		self.pylToHtmlResult+=str("""
				<p>""")
		self.pylToHtmlResult+=str("""Congratulation,""")
		self.pylToHtmlResult+=str(""" now""")
		self.pylToHtmlResult+=str(""" you""")
		self.pylToHtmlResult+=str(""" can""")
		self.pylToHtmlResult+=str(""" access""")
		self.pylToHtmlResult+=str(""" to""")
		self.pylToHtmlResult+=str(""" <a href="http://localhost/py">""")
		self.pylToHtmlResult+=str("""http://localhost/py""")
		self.pylToHtmlResult+=str("""</a>""")
		self.pylToHtmlResult+=str(""" instead""")
		self.pylToHtmlResult+=str(""" of""")
		self.pylToHtmlResult+=str(""" http://localhost/hellopy.pyl""")
		self.pylToHtmlResult+=str(""" to""")
		self.pylToHtmlResult+=str(""" see""")
		self.pylToHtmlResult+=str(""" hello""")
		self.pylToHtmlResult+=str(""" pylatte.""")
		self.pylToHtmlResult+=str("""</p>""")
		self.pylToHtmlResult+=str("""
				
			<h2>""")
		self.pylToHtmlResult+=str("""Filter""")
		self.pylToHtmlResult+=str("""</h2>""")
		self.pylToHtmlResult+=str("""
				<p>""")
		self.pylToHtmlResult+=str("""Sometimes,""")
		self.pylToHtmlResult+=str(""" we""")
		self.pylToHtmlResult+=str(""" need""")
		self.pylToHtmlResult+=str(""" to""")
		self.pylToHtmlResult+=str(""" process""")
		self.pylToHtmlResult+=str(""" one""")
		self.pylToHtmlResult+=str(""" same""")
		self.pylToHtmlResult+=str(""" function""")
		self.pylToHtmlResult+=str(""" in""")
		self.pylToHtmlResult+=str(""" many""")
		self.pylToHtmlResult+=str(""" pages""")
		self.pylToHtmlResult+=str(""" before""")
		self.pylToHtmlResult+=str(""" the""")
		self.pylToHtmlResult+=str(""" pages""")
		self.pylToHtmlResult+=str(""" get""")
		self.pylToHtmlResult+=str(""" started.""")
		self.pylToHtmlResult+=str(""" Filter""")
		self.pylToHtmlResult+=str(""" module""")
		self.pylToHtmlResult+=str(""" on""")
		self.pylToHtmlResult+=str(""" Pylatte""")
		self.pylToHtmlResult+=str(""" perfectly""")
		self.pylToHtmlResult+=str(""" supports""")
		self.pylToHtmlResult+=str(""" this.""")
		self.pylToHtmlResult+=str("""</p>""")
		self.pylToHtmlResult+=str("""
				<p>""")
		self.pylToHtmlResult+=str("""It""")
		self.pylToHtmlResult+=str(""" can""")
		self.pylToHtmlResult+=str(""" be""")
		self.pylToHtmlResult+=str(""" configured""")
		self.pylToHtmlResult+=str(""" in""")
		self.pylToHtmlResult+=str(""" <i>""")
		self.pylToHtmlResult+=str("""pylatte_config.xml""")
		self.pylToHtmlResult+=str("""</i>""")
		self.pylToHtmlResult+=str(""".""")
		self.pylToHtmlResult+=str("""</p>""")
		self.pylToHtmlResult+=str("""
				<pre class="brush: xml">""")
		self.pylToHtmlResult+=str("""
					<filter>""")
		self.pylToHtmlResult+=str("""
						<filter-name>""")
		self.pylToHtmlResult+=str("""testFilter""")
		self.pylToHtmlResult+=str("""</filter-name>""")
		self.pylToHtmlResult+=str("""
						<filter-pyl>""")
		self.pylToHtmlResult+=str("""filter/filter.pyl""")
		self.pylToHtmlResult+=str("""</filter-pyl>""")
		self.pylToHtmlResult+=str("""
					</filter>""")
		self.pylToHtmlResult+=str("""
					<filter-mapping>""")
		self.pylToHtmlResult+=str("""
						<filter-name>""")
		self.pylToHtmlResult+=str("""testFilter""")
		self.pylToHtmlResult+=str("""</filter-name>""")
		self.pylToHtmlResult+=str("""
						<filter-url>""")
		self.pylToHtmlResult+=str("""hellopy.pyl""")
		self.pylToHtmlResult+=str("""</filter-url>""")
		self.pylToHtmlResult+=str("""
						<filter-url>""")
		self.pylToHtmlResult+=str("""byepy.pyl""")
		self.pylToHtmlResult+=str("""</filter-url>""")
		self.pylToHtmlResult+=str("""
					</filter-mapping>""")
		self.pylToHtmlResult+=str("""
				</pre>""")
		self.pylToHtmlResult+=str("""
				<p>""")
		self.pylToHtmlResult+=str("""Look""")
		self.pylToHtmlResult+=str(""" at""")
		self.pylToHtmlResult+=str(""" this""")
		self.pylToHtmlResult+=str(""" xml""")
		self.pylToHtmlResult+=str(""" code.""")
		self.pylToHtmlResult+=str(""" &lt;filter-name&gt;""")
		self.pylToHtmlResult+=str(""" value(e.g.""")
		self.pylToHtmlResult+=str(""" testFilter)""")
		self.pylToHtmlResult+=str(""" in""")
		self.pylToHtmlResult+=str(""" &lt;filter&gt;""")
		self.pylToHtmlResult+=str(""" and""")
		self.pylToHtmlResult+=str(""" &lt;filter-mapping&gt;""")
		self.pylToHtmlResult+=str(""" is""")
		self.pylToHtmlResult+=str(""" just""")
		self.pylToHtmlResult+=str(""" name""")
		self.pylToHtmlResult+=str(""" to""")
		self.pylToHtmlResult+=str(""" identify""")
		self.pylToHtmlResult+=str(""" each""")
		self.pylToHtmlResult+=str(""" filter""")
		self.pylToHtmlResult+=str(""" information.""")
		self.pylToHtmlResult+=str("""</p>""")
		self.pylToHtmlResult+=str("""
				<p>""")
		self.pylToHtmlResult+=str("""&lt;filter-pyl&gt;""")
		self.pylToHtmlResult+=str(""" value""")
		self.pylToHtmlResult+=str(""" will""")
		self.pylToHtmlResult+=str(""" be""")
		self.pylToHtmlResult+=str(""" executed""")
		self.pylToHtmlResult+=str(""" at""")
		self.pylToHtmlResult+=str(""" first""")
		self.pylToHtmlResult+=str(""" when""")
		self.pylToHtmlResult+=str(""" you""")
		self.pylToHtmlResult+=str(""" access""")
		self.pylToHtmlResult+=str(""" to""")
		self.pylToHtmlResult+=str(""" &lt;filter-url&gt;""")
		self.pylToHtmlResult+=str(""" values.""")
		self.pylToHtmlResult+=str("""</p>""")
		self.pylToHtmlResult+=str("""
				<p>""")
		self.pylToHtmlResult+=str("""For""")
		self.pylToHtmlResult+=str(""" instance,""")
		self.pylToHtmlResult+=str(""" filter/filter.pyl""")
		self.pylToHtmlResult+=str(""" will""")
		self.pylToHtmlResult+=str(""" be""")
		self.pylToHtmlResult+=str(""" executed""")
		self.pylToHtmlResult+=str(""" at""")
		self.pylToHtmlResult+=str(""" first""")
		self.pylToHtmlResult+=str(""" when""")
		self.pylToHtmlResult+=str(""" you""")
		self.pylToHtmlResult+=str(""" access""")
		self.pylToHtmlResult+=str(""" to""")
		self.pylToHtmlResult+=str(""" byepy.pyl""")
		self.pylToHtmlResult+=str(""" or""")
		self.pylToHtmlResult+=str(""" hellopy.pyl""")
		self.pylToHtmlResult+=str(""" in""")
		self.pylToHtmlResult+=str(""" the""")
		self.pylToHtmlResult+=str(""" code.""")
		self.pylToHtmlResult+=str("""</p>""")
		self.pylToHtmlResult+=str("""
				<p>""")
		self.pylToHtmlResult+=str("""So""")
		self.pylToHtmlResult+=str(""" you""")
		self.pylToHtmlResult+=str(""" don't""")
		self.pylToHtmlResult+=str(""" need""")
		self.pylToHtmlResult+=str(""" to""")
		self.pylToHtmlResult+=str(""" add""")
		self.pylToHtmlResult+=str(""" same""")
		self.pylToHtmlResult+=str(""" code""")
		self.pylToHtmlResult+=str(""" to""")
		self.pylToHtmlResult+=str(""" many""")
		self.pylToHtmlResult+=str(""" pages""")
		self.pylToHtmlResult+=str(""" which""")
		self.pylToHtmlResult+=str(""" require""")
		self.pylToHtmlResult+=str(""" same""")
		self.pylToHtmlResult+=str(""" function""")
		self.pylToHtmlResult+=str(""" anymore.""")
		self.pylToHtmlResult+=str("""</p>""")
		self.pylToHtmlResult+=str("""
				
			<h2>""")
		self.pylToHtmlResult+=str("""GET""")
		self.pylToHtmlResult+=str(""" &""")
		self.pylToHtmlResult+=str(""" POST""")
		self.pylToHtmlResult+=str("""</h2>""")
		self.pylToHtmlResult+=str("""
				<p>""")
		self.pylToHtmlResult+=str("""There""")
		self.pylToHtmlResult+=str(""" are""")
		self.pylToHtmlResult+=str(""" two""")
		self.pylToHtmlResult+=str(""" kinds""")
		self.pylToHtmlResult+=str(""" of""")
		self.pylToHtmlResult+=str(""" method""")
		self.pylToHtmlResult+=str(""" to""")
		self.pylToHtmlResult+=str(""" deal""")
		self.pylToHtmlResult+=str(""" with""")
		self.pylToHtmlResult+=str(""" GET""")
		self.pylToHtmlResult+=str(""" &""")
		self.pylToHtmlResult+=str(""" POST""")
		self.pylToHtmlResult+=str(""" parameter.""")
		self.pylToHtmlResult+=str("""</p>""")
		self.pylToHtmlResult+=str("""
				<p>""")
		self.pylToHtmlResult+=str("""When""")
		self.pylToHtmlResult+=str(""" you""")
		self.pylToHtmlResult+=str(""" request""")
		self.pylToHtmlResult+=str(""" some""")
		self.pylToHtmlResult+=str(""" parameter""")
		self.pylToHtmlResult+=str(""" values""")
		self.pylToHtmlResult+=str(""" using""")
		self.pylToHtmlResult+=str(""" GET""")
		self.pylToHtmlResult+=str(""" method""")
		self.pylToHtmlResult+=str(""" or""")
		self.pylToHtmlResult+=str(""" POST""")
		self.pylToHtmlResult+=str(""" method,""")
		self.pylToHtmlResult+=str(""" you""")
		self.pylToHtmlResult+=str(""" can""")
		self.pylToHtmlResult+=str(""" get""")
		self.pylToHtmlResult+=str(""" the""")
		self.pylToHtmlResult+=str(""" parameter""")
		self.pylToHtmlResult+=str(""" values""")
		self.pylToHtmlResult+=str(""" as""")
		self.pylToHtmlResult+=str(""" following.""")
		self.pylToHtmlResult+=str("""</p>""")
		self.pylToHtmlResult+=str("""
				<pre class="brush: xml">""")
		self.pylToHtmlResult+=str("""
					&lt;$=param$&gt;""")
		self.pylToHtmlResult+=str("""
				</pre>""")
		self.pylToHtmlResult+=str("""
				<p>""")
		self.pylToHtmlResult+=str("""The""")
		self.pylToHtmlResult+=str(""" variable""")
		self.pylToHtmlResult+=str(""" <b>""")
		self.pylToHtmlResult+=str("""param""")
		self.pylToHtmlResult+=str("""</b>""")
		self.pylToHtmlResult+=str(""" has""")
		self.pylToHtmlResult+=str(""" all""")
		self.pylToHtmlResult+=str(""" requested""")
		self.pylToHtmlResult+=str(""" values""")
		self.pylToHtmlResult+=str(""" as""")
		self.pylToHtmlResult+=str(""" dictionary""")
		self.pylToHtmlResult+=str(""" type""")
		self.pylToHtmlResult+=str(""" like""")
		self.pylToHtmlResult+=str(""" <i>""")
		self.pylToHtmlResult+=str("""{"id":pylatte,""")
		self.pylToHtmlResult+=str(""" "password":python}""")
		self.pylToHtmlResult+=str("""</i>""")
		self.pylToHtmlResult+=str(""".""")
		self.pylToHtmlResult+=str(""" Definately,""")
		self.pylToHtmlResult+=str(""" you""")
		self.pylToHtmlResult+=str(""" can""")
		self.pylToHtmlResult+=str(""" get""")
		self.pylToHtmlResult+=str(""" specific""")
		self.pylToHtmlResult+=str(""" value""")
		self.pylToHtmlResult+=str(""" such""")
		self.pylToHtmlResult+=str(""" as""")
		self.pylToHtmlResult+=str(""" following.""")
		self.pylToHtmlResult+=str("""</p>""")
		self.pylToHtmlResult+=str(""" 
				<pre class="brush: xml">""")
		self.pylToHtmlResult+=str("""
					&lt;$=param[&quot;id&quot;]$&gt;""")
		self.pylToHtmlResult+=str("""
				</pre>""")
		self.pylToHtmlResult+=str("""
				<p>""")
		self.pylToHtmlResult+=str("""Pylatte""")
		self.pylToHtmlResult+=str(""" does""")
		self.pylToHtmlResult+=str(""" not""")
		self.pylToHtmlResult+=str(""" support""")
		self.pylToHtmlResult+=str(""" the""")
		self.pylToHtmlResult+=str(""" other""")
		self.pylToHtmlResult+=str(""" methods""")
		self.pylToHtmlResult+=str(""" like""")
		self.pylToHtmlResult+=str(""" PUT,""")
		self.pylToHtmlResult+=str(""" DELETE.""")
		self.pylToHtmlResult+=str("""</p>""")
		self.pylToHtmlResult+=str("""
				
			<h2>""")
		self.pylToHtmlResult+=str("""Session""")
		self.pylToHtmlResult+=str("""</h2>""")
		self.pylToHtmlResult+=str("""
				<p>""")
		self.pylToHtmlResult+=str("""Pylatte""")
		self.pylToHtmlResult+=str(""" supports""")
		self.pylToHtmlResult+=str(""" sesson""")
		self.pylToHtmlResult+=str(""" management""")
		self.pylToHtmlResult+=str(""" allocating""")
		self.pylToHtmlResult+=str(""" session""")
		self.pylToHtmlResult+=str(""" datas""")
		self.pylToHtmlResult+=str(""" for""")
		self.pylToHtmlResult+=str(""" each""")
		self.pylToHtmlResult+=str(""" accessor.""")
		self.pylToHtmlResult+=str("""</p>""")
		self.pylToHtmlResult+=str("""
				<p>""")
		self.pylToHtmlResult+=str("""This""")
		self.pylToHtmlResult+=str(""" session""")
		self.pylToHtmlResult+=str(""" data""")
		self.pylToHtmlResult+=str(""" type""")
		self.pylToHtmlResult+=str(""" is""")
		self.pylToHtmlResult+=str(""" dictionary.""")
		self.pylToHtmlResult+=str(""" The""")
		self.pylToHtmlResult+=str(""" way""")
		self.pylToHtmlResult+=str(""" to""")
		self.pylToHtmlResult+=str(""" use""")
		self.pylToHtmlResult+=str(""" is""")
		self.pylToHtmlResult+=str(""" similar""")
		self.pylToHtmlResult+=str(""" with""")
		self.pylToHtmlResult+=str(""" GET""")
		self.pylToHtmlResult+=str(""" &""")
		self.pylToHtmlResult+=str(""" POST""")
		self.pylToHtmlResult+=str(""" above.""")
		self.pylToHtmlResult+=str(""" Refer""")
		self.pylToHtmlResult+=str(""" to""")
		self.pylToHtmlResult+=str(""" following""")
		self.pylToHtmlResult+=str(""" code.""")
		self.pylToHtmlResult+=str("""</p>""")
		self.pylToHtmlResult+=str("""
				<pre class="brush: xml">""")
		self.pylToHtmlResult+=str("""
					session[&quot;name&quot;]""")
		self.pylToHtmlResult+=str(""" =""")
		self.pylToHtmlResult+=str(""" &quot;pylatte&quot;""")
		self.pylToHtmlResult+=str("""
					session[&quot;age&quot;]""")
		self.pylToHtmlResult+=str(""" =""")
		self.pylToHtmlResult+=str(""" 1""")
		self.pylToHtmlResult+=str("""
				</pre>""")
		self.pylToHtmlResult+=str("""
				<p>""")
		self.pylToHtmlResult+=str("""Pylatte""")
		self.pylToHtmlResult+=str(""" manages""")
		self.pylToHtmlResult+=str(""" session""")
		self.pylToHtmlResult+=str(""" data""")
		self.pylToHtmlResult+=str(""" through""")
		self.pylToHtmlResult+=str(""" session""")
		self.pylToHtmlResult+=str(""" module.""")
		self.pylToHtmlResult+=str(""" Usually,""")
		self.pylToHtmlResult+=str(""" it""")
		self.pylToHtmlResult+=str(""" is""")
		self.pylToHtmlResult+=str(""" required""")
		self.pylToHtmlResult+=str(""" to""")
		self.pylToHtmlResult+=str(""" use""")
		self.pylToHtmlResult+=str(""" in""")
		self.pylToHtmlResult+=str(""" membership""")
		self.pylToHtmlResult+=str(""" page""")
		self.pylToHtmlResult+=str(""" to""")
		self.pylToHtmlResult+=str(""" deal""")
		self.pylToHtmlResult+=str(""" with""")
		self.pylToHtmlResult+=str(""" each""")
		self.pylToHtmlResult+=str(""" member's""")
		self.pylToHtmlResult+=str(""" session""")
		self.pylToHtmlResult+=str(""" data.""")
		self.pylToHtmlResult+=str(""" </p>""")
		self.pylToHtmlResult+=str("""

			<h2>""")
		self.pylToHtmlResult+=str("""File""")
		self.pylToHtmlResult+=str(""" Upload""")
		self.pylToHtmlResult+=str("""</h2>""")
		self.pylToHtmlResult+=str("""
				<p>""")
		self.pylToHtmlResult+=str("""You""")
		self.pylToHtmlResult+=str(""" can""")
		self.pylToHtmlResult+=str(""" implement""")
		self.pylToHtmlResult+=str(""" file""")
		self.pylToHtmlResult+=str(""" upload""")
		self.pylToHtmlResult+=str(""" function""")
		self.pylToHtmlResult+=str(""" with""")
		self.pylToHtmlResult+=str(""" a""")
		self.pylToHtmlResult+=str(""" file""")
		self.pylToHtmlResult+=str(""" upload""")
		self.pylToHtmlResult+=str(""" module""")
		self.pylToHtmlResult+=str(""" on""")
		self.pylToHtmlResult+=str(""" Pylatte.""")
		self.pylToHtmlResult+=str(""" When""")
		self.pylToHtmlResult+=str(""" you""")
		self.pylToHtmlResult+=str(""" use""")
		self.pylToHtmlResult+=str(""" &lt;form&gt;""")
		self.pylToHtmlResult+=str(""" tag,""")
		self.pylToHtmlResult+=str(""" it""")
		self.pylToHtmlResult+=str(""" is""")
		self.pylToHtmlResult+=str(""" compulsory""")
		self.pylToHtmlResult+=str(""" to""")
		self.pylToHtmlResult+=str(""" put""")
		self.pylToHtmlResult+=str(""" attribute""")
		self.pylToHtmlResult+=str(""" :""")
		self.pylToHtmlResult+=str(""" <b>""")
		self.pylToHtmlResult+=str("""enctype="multipart/form-data""")
		self.pylToHtmlResult+=str("""</b>""")
		self.pylToHtmlResult+=str(""" into""")
		self.pylToHtmlResult+=str(""" the""")
		self.pylToHtmlResult+=str(""" tag.""")
		self.pylToHtmlResult+=str("""</p>""")
		self.pylToHtmlResult+=str("""
				<pre class="brush: xml">""")
		self.pylToHtmlResult+=str("""
				
					<form  method="post" enctype="multipart/form-data" action="http:/localhost/pageToProcessPost">""")
		self.pylToHtmlResult+=str("""
						<input type="file" name="filepy" />""")
		self.pylToHtmlResult+=str("""
						<input type="sudmit" value="click" />""")
		self.pylToHtmlResult+=str("""
					</form>""")
		self.pylToHtmlResult+=str("""
				</pre>""")
		self.pylToHtmlResult+=str("""
				<p>""")
		self.pylToHtmlResult+=str("""Now""")
		self.pylToHtmlResult+=str(""" you""")
		self.pylToHtmlResult+=str(""" can""")
		self.pylToHtmlResult+=str(""" upload""")
		self.pylToHtmlResult+=str(""" a""")
		self.pylToHtmlResult+=str(""" file""")
		self.pylToHtmlResult+=str(""" as""")
		self.pylToHtmlResult+=str(""" post""")
		self.pylToHtmlResult+=str(""" parameters""")
		self.pylToHtmlResult+=str(""" in""")
		self.pylToHtmlResult+=str(""" pageToProcessPost(This""")
		self.pylToHtmlResult+=str(""" is""")
		self.pylToHtmlResult+=str(""" a""")
		self.pylToHtmlResult+=str(""" mapped""")
		self.pylToHtmlResult+=str(""" page""")
		self.pylToHtmlResult+=str(""" name""")
		self.pylToHtmlResult+=str(""" by""")
		self.pylToHtmlResult+=str(""" mapping""")
		self.pylToHtmlResult+=str(""" module""")
		self.pylToHtmlResult+=str(""" at""")
		self.pylToHtmlResult+=str(""" <i>""")
		self.pylToHtmlResult+=str("""pylatte_config.xml""")
		self.pylToHtmlResult+=str("""</i>""")
		self.pylToHtmlResult+=str(""")""")
		self.pylToHtmlResult+=str(""" page.""")
		self.pylToHtmlResult+=str(""" Refer""")
		self.pylToHtmlResult+=str(""" to""")
		self.pylToHtmlResult+=str(""" following""")
		self.pylToHtmlResult+=str(""" code.""")
		self.pylToHtmlResult+=str("""</p>""")
		self.pylToHtmlResult+=str("""
				<pre class="brush: xml">""")
		self.pylToHtmlResult+=str("""
					&lt;$""")
		self.pylToHtmlResult+=str("""
					pyformFile=formFile.formFile(pyFile)""")
		self.pylToHtmlResult+=str("""
					pyformFile.moveUploadFile(&quot;filepy&quot;,&quot;download&quot;,&quot;pylatte.jpg&quot;)""")
		self.pylToHtmlResult+=str("""
					$&gt;""")
		self.pylToHtmlResult+=str("""
				</pre>""")
		self.pylToHtmlResult+=str("""
				<p>""")
		self.pylToHtmlResult+=str("""you""")
		self.pylToHtmlResult+=str(""" can""")
		self.pylToHtmlResult+=str(""" receive""")
		self.pylToHtmlResult+=str(""" the""")
		self.pylToHtmlResult+=str(""" file""")
		self.pylToHtmlResult+=str(""" information""")
		self.pylToHtmlResult+=str(""" to""")
		self.pylToHtmlResult+=str(""" variable""")
		self.pylToHtmlResult+=str(""" with""")
		self.pylToHtmlResult+=str(""" using""")
		self.pylToHtmlResult+=str(""" <b>""")
		self.pylToHtmlResult+=str("""formFile.formFile(pyFile)""")
		self.pylToHtmlResult+=str("""</b>""")
		self.pylToHtmlResult+=str(""".""")
		self.pylToHtmlResult+=str(""" And""")
		self.pylToHtmlResult+=str(""" execute""")
		self.pylToHtmlResult+=str(""" moveUploadFile""")
		self.pylToHtmlResult+=str(""" mothod""")
		self.pylToHtmlResult+=str(""" from""")
		self.pylToHtmlResult+=str(""" the""")
		self.pylToHtmlResult+=str(""" variable""")
		self.pylToHtmlResult+=str(""" to""")
		self.pylToHtmlResult+=str(""" complete""")
		self.pylToHtmlResult+=str(""" upload""")
		self.pylToHtmlResult+=str(""" file""")
		self.pylToHtmlResult+=str(""" to""")
		self.pylToHtmlResult+=str(""" server.""")
		self.pylToHtmlResult+=str(""" Parameters""")
		self.pylToHtmlResult+=str(""" of""")
		self.pylToHtmlResult+=str(""" moveUploadFile""")
		self.pylToHtmlResult+=str(""" are""")
		self.pylToHtmlResult+=str(""" name,""")
		self.pylToHtmlResult+=str(""" folder""")
		self.pylToHtmlResult+=str(""" name,""")
		self.pylToHtmlResult+=str(""" and""")
		self.pylToHtmlResult+=str(""" file""")
		self.pylToHtmlResult+=str(""" name""")
		self.pylToHtmlResult+=str(""" in""")
		self.pylToHtmlResult+=str(""" order.""")
		self.pylToHtmlResult+=str("""</p>""")
		self.pylToHtmlResult+=str(""" 
				<p>""")
		self.pylToHtmlResult+=str("""In""")
		self.pylToHtmlResult+=str(""" addition,""")
		self.pylToHtmlResult+=str(""" pyFile[""")
		self.pylToHtmlResult+=str("""<i>""")
		self.pylToHtmlResult+=str("""name""")
		self.pylToHtmlResult+=str("""</i>""")
		self.pylToHtmlResult+=str("""]""")
		self.pylToHtmlResult+=str("""</p>""")
		self.pylToHtmlResult+=str(""" has""")
		self.pylToHtmlResult+=str(""" a""")
		self.pylToHtmlResult+=str(""" little""")
		self.pylToHtmlResult+=str(""" information""")
		self.pylToHtmlResult+=str(""" about""")
		self.pylToHtmlResult+=str(""" the""")
		self.pylToHtmlResult+=str(""" file""")
		self.pylToHtmlResult+=str(""" as""")
		self.pylToHtmlResult+=str(""" dictionary""")
		self.pylToHtmlResult+=str(""" type.""")
		self.pylToHtmlResult+=str("""
			
			<h2>""")
		self.pylToHtmlResult+=str("""Database""")
		self.pylToHtmlResult+=str("""</h2>""")
		self.pylToHtmlResult+=str("""
				<p>""")
		self.pylToHtmlResult+=str("""First""")
		self.pylToHtmlResult+=str(""" of""")
		self.pylToHtmlResult+=str(""" all,""")
		self.pylToHtmlResult+=str(""" to""")
		self.pylToHtmlResult+=str(""" set""")
		self.pylToHtmlResult+=str(""" your""")
		self.pylToHtmlResult+=str(""" database,""")
		self.pylToHtmlResult+=str(""" it""")
		self.pylToHtmlResult+=str(""" is""")
		self.pylToHtmlResult+=str(""" needed""")
		self.pylToHtmlResult+=str(""" to""")
		self.pylToHtmlResult+=str(""" fix""")
		self.pylToHtmlResult+=str(""" &lt;sql&gt;""")
		self.pylToHtmlResult+=str(""" values""")
		self.pylToHtmlResult+=str(""" in""")
		self.pylToHtmlResult+=str(""" <i>""")
		self.pylToHtmlResult+=str("""db_mapping.xml""")
		self.pylToHtmlResult+=str("""</i>""")
		self.pylToHtmlResult+=str(""" about""")
		self.pylToHtmlResult+=str(""" MySQL""")
		self.pylToHtmlResult+=str(""" connection""")
		self.pylToHtmlResult+=str(""" information.""")
		self.pylToHtmlResult+=str("""</p>""")
		self.pylToHtmlResult+=str("""
				<pre class="brush: xml">""")
		self.pylToHtmlResult+=str("""
					<sql db="mysql">""")
		self.pylToHtmlResult+=str("""
						<host>""")
		self.pylToHtmlResult+=str("""localhost""")
		self.pylToHtmlResult+=str("""</host>""")
		self.pylToHtmlResult+=str("""
						<user>""")
		self.pylToHtmlResult+=str("""user""")
		self.pylToHtmlResult+=str("""</user>""")
		self.pylToHtmlResult+=str("""
						<password>""")
		self.pylToHtmlResult+=str("""password""")
		self.pylToHtmlResult+=str("""</password>""")
		self.pylToHtmlResult+=str("""
						<dbName>""")
		self.pylToHtmlResult+=str("""pylatte""")
		self.pylToHtmlResult+=str("""</dbName>""")
		self.pylToHtmlResult+=str("""
					</sql>""")
		self.pylToHtmlResult+=str("""
				</pre>""")
		self.pylToHtmlResult+=str("""
				<p>""")
		self.pylToHtmlResult+=str("""Only""")
		self.pylToHtmlResult+=str(""" MySQL""")
		self.pylToHtmlResult+=str(""" is""")
		self.pylToHtmlResult+=str(""" an""")
		self.pylToHtmlResult+=str(""" available""")
		self.pylToHtmlResult+=str(""" database""")
		self.pylToHtmlResult+=str(""" on""")
		self.pylToHtmlResult+=str(""" Pylatte""")
		self.pylToHtmlResult+=str(""" now.""")
		self.pylToHtmlResult+=str(""" In""")
		self.pylToHtmlResult+=str(""" &lt;sql&gt;,""")
		self.pylToHtmlResult+=str(""" it""")
		self.pylToHtmlResult+=str(""" is""")
		self.pylToHtmlResult+=str(""" required""")
		self.pylToHtmlResult+=str(""" to""")
		self.pylToHtmlResult+=str(""" fill""")
		self.pylToHtmlResult+=str(""" with""")
		self.pylToHtmlResult+=str(""" host,""")
		self.pylToHtmlResult+=str(""" user,""")
		self.pylToHtmlResult+=str(""" password,""")
		self.pylToHtmlResult+=str(""" database""")
		self.pylToHtmlResult+=str(""" name.""")
		self.pylToHtmlResult+=str("""</p>""")
		self.pylToHtmlResult+=str("""
				
				<h3>""")
		self.pylToHtmlResult+=str("""Simple""")
		self.pylToHtmlResult+=str(""" way""")
		self.pylToHtmlResult+=str(""" to""")
		self.pylToHtmlResult+=str(""" use""")
		self.pylToHtmlResult+=str(""" database""")
		self.pylToHtmlResult+=str("""</h3>""")
		self.pylToHtmlResult+=str("""
				<p>""")
		self.pylToHtmlResult+=str("""<b>""")
		self.pylToHtmlResult+=str("""&lt;@latteDatabase&gt;""")
		self.pylToHtmlResult+=str("""</b>""")
		self.pylToHtmlResult+=str(""" has""")
		self.pylToHtmlResult+=str(""" to""")
		self.pylToHtmlResult+=str(""" be""")
		self.pylToHtmlResult+=str(""" written""")
		self.pylToHtmlResult+=str(""" on""")
		self.pylToHtmlResult+=str(""" the""")
		self.pylToHtmlResult+=str(""" code""")
		self.pylToHtmlResult+=str(""" specifically""")
		self.pylToHtmlResult+=str(""" before""")
		self.pylToHtmlResult+=str(""" using""")
		self.pylToHtmlResult+=str(""" database.""")
		self.pylToHtmlResult+=str(""" After""")
		self.pylToHtmlResult+=str(""" that,""")
		self.pylToHtmlResult+=str(""" execute""")
		self.pylToHtmlResult+=str(""" SQL""")
		self.pylToHtmlResult+=str(""" what""")
		self.pylToHtmlResult+=str(""" you""")
		self.pylToHtmlResult+=str(""" need""")
		self.pylToHtmlResult+=str(""" through""")
		self.pylToHtmlResult+=str(""" <b>""")
		self.pylToHtmlResult+=str("""latteDB.query()""")
		self.pylToHtmlResult+=str("""</b>""")
		self.pylToHtmlResult+=str(""" method.""")
		self.pylToHtmlResult+=str(""" And""")
		self.pylToHtmlResult+=str(""" then,""")
		self.pylToHtmlResult+=str(""" use""")
		self.pylToHtmlResult+=str(""" <b>""")
		self.pylToHtmlResult+=str("""latteDB.store_result()""")
		self.pylToHtmlResult+=str("""</b>""")
		self.pylToHtmlResult+=str(""" method""")
		self.pylToHtmlResult+=str(""" which""")
		self.pylToHtmlResult+=str(""" return""")
		self.pylToHtmlResult+=str(""" result""")
		self.pylToHtmlResult+=str(""" of""")
		self.pylToHtmlResult+=str(""" processing""")
		self.pylToHtmlResult+=str(""" the""")
		self.pylToHtmlResult+=str(""" SQL.""")
		self.pylToHtmlResult+=str("""</p>""")
		self.pylToHtmlResult+=str("""
				<p>""")
		self.pylToHtmlResult+=str("""The""")
		self.pylToHtmlResult+=str(""" result""")
		self.pylToHtmlResult+=str(""" include""")
		self.pylToHtmlResult+=str(""" not""")
		self.pylToHtmlResult+=str(""" only""")
		self.pylToHtmlResult+=str(""" result""")
		self.pylToHtmlResult+=str(""" of""")
		self.pylToHtmlResult+=str(""" SQL""")
		self.pylToHtmlResult+=str(""" but""")
		self.pylToHtmlResult+=str(""" also""")
		self.pylToHtmlResult+=str(""" some""")
		self.pylToHtmlResult+=str(""" methods.""")
		self.pylToHtmlResult+=str(""" To""")
		self.pylToHtmlResult+=str(""" see""")
		self.pylToHtmlResult+=str(""" how""")
		self.pylToHtmlResult+=str(""" to""")
		self.pylToHtmlResult+=str(""" use""")
		self.pylToHtmlResult+=str(""" a""")
		self.pylToHtmlResult+=str(""" database,""")
		self.pylToHtmlResult+=str(""" check""")
		self.pylToHtmlResult+=str(""" example""")
		self.pylToHtmlResult+=str(""" code""")
		self.pylToHtmlResult+=str(""" below.""")
		self.pylToHtmlResult+=str("""</p>""")
		self.pylToHtmlResult+=str("""
				<pre class="brush: xml">""")
		self.pylToHtmlResult+=str("""
					&lt;$""")
		self.pylToHtmlResult+=str("""
					latteDatabase()""")
		self.pylToHtmlResult+=str("""
					latteDB.query(&quot;select""")
		self.pylToHtmlResult+=str(""" *""")
		self.pylToHtmlResult+=str(""" from""")
		self.pylToHtmlResult+=str(""" test&quot;)""")
		self.pylToHtmlResult+=str("""
					result=latteDB.store_result()""")
		self.pylToHtmlResult+=str("""
					$&gt;""")
		self.pylToHtmlResult+=str("""
					&lt;div""")
		self.pylToHtmlResult+=str(""" id="dbdiv"&gt;""")
		self.pylToHtmlResult+=str("""
					&lt;$=result.fetch_row()$&gt;""")
		self.pylToHtmlResult+=str("""
					&lt;/div&gt;""")
		self.pylToHtmlResult+=str("""
				</pre>""")
		self.pylToHtmlResult+=str("""
				<p>""")
		self.pylToHtmlResult+=str("""This""")
		self.pylToHtmlResult+=str(""" code""")
		self.pylToHtmlResult+=str(""" returns""")
		self.pylToHtmlResult+=str(""" tuple""")
		self.pylToHtmlResult+=str(""" type""")
		self.pylToHtmlResult+=str(""" result""")
		self.pylToHtmlResult+=str(""" by""")
		self.pylToHtmlResult+=str(""" fetch_row()""")
		self.pylToHtmlResult+=str("""</p>""")
		self.pylToHtmlResult+=str("""
				<p>""")
		self.pylToHtmlResult+=str("""<b>""")
		self.pylToHtmlResult+=str("""fetch_row()""")
		self.pylToHtmlResult+=str("""</b>""")
		self.pylToHtmlResult+=str(""" method""")
		self.pylToHtmlResult+=str(""" takes""")
		self.pylToHtmlResult+=str(""" some""")
		self.pylToHtmlResult+=str(""" additional""")
		self.pylToHtmlResult+=str(""" parameters.""")
		self.pylToHtmlResult+=str(""" </p>""")
		self.pylToHtmlResult+=str("""
				<p>""")
		self.pylToHtmlResult+=str("""The""")
		self.pylToHtmlResult+=str(""" first""")
		self.pylToHtmlResult+=str(""" one""")
		self.pylToHtmlResult+=str(""" is,""")
		self.pylToHtmlResult+=str(""" how""")
		self.pylToHtmlResult+=str(""" many""")
		self.pylToHtmlResult+=str(""" rows""")
		self.pylToHtmlResult+=str(""" (maxrows)""")
		self.pylToHtmlResult+=str(""" should""")
		self.pylToHtmlResult+=str(""" be""")
		self.pylToHtmlResult+=str(""" returned.""")
		self.pylToHtmlResult+=str(""" By""")
		self.pylToHtmlResult+=str(""" default,""")
		self.pylToHtmlResult+=str(""" it""")
		self.pylToHtmlResult+=str(""" returns""")
		self.pylToHtmlResult+=str(""" one""")
		self.pylToHtmlResult+=str(""" row.""")
		self.pylToHtmlResult+=str(""" It""")
		self.pylToHtmlResult+=str(""" may""")
		self.pylToHtmlResult+=str(""" return""")
		self.pylToHtmlResult+=str(""" fewer""")
		self.pylToHtmlResult+=str(""" rows""")
		self.pylToHtmlResult+=str(""" than""")
		self.pylToHtmlResult+=str(""" you""")
		self.pylToHtmlResult+=str(""" asked""")
		self.pylToHtmlResult+=str(""" for,""")
		self.pylToHtmlResult+=str(""" but""")
		self.pylToHtmlResult+=str(""" never""")
		self.pylToHtmlResult+=str(""" more.""")
		self.pylToHtmlResult+=str(""" If""")
		self.pylToHtmlResult+=str(""" you""")
		self.pylToHtmlResult+=str(""" set""")
		self.pylToHtmlResult+=str(""" maxrows=0,""")
		self.pylToHtmlResult+=str(""" it""")
		self.pylToHtmlResult+=str(""" returns""")
		self.pylToHtmlResult+=str(""" all""")
		self.pylToHtmlResult+=str(""" rows""")
		self.pylToHtmlResult+=str(""" of""")
		self.pylToHtmlResult+=str(""" the""")
		self.pylToHtmlResult+=str(""" result""")
		self.pylToHtmlResult+=str(""" set.""")
		self.pylToHtmlResult+=str(""" If""")
		self.pylToHtmlResult+=str(""" you""")
		self.pylToHtmlResult+=str(""" ever""")
		self.pylToHtmlResult+=str(""" get""")
		self.pylToHtmlResult+=str(""" an""")
		self.pylToHtmlResult+=str(""" empty""")
		self.pylToHtmlResult+=str(""" tuple""")
		self.pylToHtmlResult+=str(""" back,""")
		self.pylToHtmlResult+=str(""" you""")
		self.pylToHtmlResult+=str(""" ran""")
		self.pylToHtmlResult+=str(""" out""")
		self.pylToHtmlResult+=str(""" of""")
		self.pylToHtmlResult+=str(""" rows.""")
		self.pylToHtmlResult+=str("""</p>""")
		self.pylToHtmlResult+=str("""
				<pt>""")
		self.pylToHtmlResult+=str("""The""")
		self.pylToHtmlResult+=str(""" second""")
		self.pylToHtmlResult+=str(""" parameter""")
		self.pylToHtmlResult+=str(""" (how)""")
		self.pylToHtmlResult+=str(""" tells""")
		self.pylToHtmlResult+=str(""" it""")
		self.pylToHtmlResult+=str(""" how""")
		self.pylToHtmlResult+=str(""" the""")
		self.pylToHtmlResult+=str(""" row""")
		self.pylToHtmlResult+=str(""" should""")
		self.pylToHtmlResult+=str(""" be""")
		self.pylToHtmlResult+=str(""" represented.""")
		self.pylToHtmlResult+=str(""" By""")
		self.pylToHtmlResult+=str(""" default,""")
		self.pylToHtmlResult+=str(""" it""")
		self.pylToHtmlResult+=str(""" is""")
		self.pylToHtmlResult+=str(""" zero""")
		self.pylToHtmlResult+=str(""" which""")
		self.pylToHtmlResult+=str(""" means,""")
		self.pylToHtmlResult+=str(""" return""")
		self.pylToHtmlResult+=str(""" as""")
		self.pylToHtmlResult+=str(""" a""")
		self.pylToHtmlResult+=str(""" tuple.""")
		self.pylToHtmlResult+=str(""" how=1""")
		self.pylToHtmlResult+=str(""" means,""")
		self.pylToHtmlResult+=str(""" return""")
		self.pylToHtmlResult+=str(""" it""")
		self.pylToHtmlResult+=str(""" as""")
		self.pylToHtmlResult+=str(""" a""")
		self.pylToHtmlResult+=str(""" dictionary,""")
		self.pylToHtmlResult+=str(""" where""")
		self.pylToHtmlResult+=str(""" the""")
		self.pylToHtmlResult+=str(""" keys""")
		self.pylToHtmlResult+=str(""" are""")
		self.pylToHtmlResult+=str(""" the""")
		self.pylToHtmlResult+=str(""" column""")
		self.pylToHtmlResult+=str(""" names,""")
		self.pylToHtmlResult+=str(""" or""")
		self.pylToHtmlResult+=str(""" table.column""")
		self.pylToHtmlResult+=str(""" if""")
		self.pylToHtmlResult+=str(""" there""")
		self.pylToHtmlResult+=str(""" are""")
		self.pylToHtmlResult+=str(""" two""")
		self.pylToHtmlResult+=str(""" columns""")
		self.pylToHtmlResult+=str(""" with""")
		self.pylToHtmlResult+=str(""" the""")
		self.pylToHtmlResult+=str(""" same""")
		self.pylToHtmlResult+=str(""" name""")
		self.pylToHtmlResult+=str(""" (say,""")
		self.pylToHtmlResult+=str(""" from""")
		self.pylToHtmlResult+=str(""" a""")
		self.pylToHtmlResult+=str(""" join).""")
		self.pylToHtmlResult+=str(""" how=2""")
		self.pylToHtmlResult+=str(""" means""")
		self.pylToHtmlResult+=str(""" the""")
		self.pylToHtmlResult+=str(""" same""")
		self.pylToHtmlResult+=str(""" as""")
		self.pylToHtmlResult+=str(""" how=1""")
		self.pylToHtmlResult+=str(""" except""")
		self.pylToHtmlResult+=str(""" that""")
		self.pylToHtmlResult+=str(""" the""")
		self.pylToHtmlResult+=str(""" keys""")
		self.pylToHtmlResult+=str(""" are""")
		self.pylToHtmlResult+=str(""" always""")
		self.pylToHtmlResult+=str(""" table.column.""")
		self.pylToHtmlResult+=str("""</p>""")
		self.pylToHtmlResult+=str("""
				
				<h3>""")
		self.pylToHtmlResult+=str("""Advanced""")
		self.pylToHtmlResult+=str(""" way""")
		self.pylToHtmlResult+=str(""" to""")
		self.pylToHtmlResult+=str(""" use""")
		self.pylToHtmlResult+=str(""" database""")
		self.pylToHtmlResult+=str("""</h3>""")
		self.pylToHtmlResult+=str("""
				<p>""")
		self.pylToHtmlResult+=str("""<b>""")
		self.pylToHtmlResult+=str("""&lt;@latteDatabaseExt&gt;""")
		self.pylToHtmlResult+=str("""</b>""")
		self.pylToHtmlResult+=str(""" has""")
		self.pylToHtmlResult+=str(""" to""")
		self.pylToHtmlResult+=str(""" be""")
		self.pylToHtmlResult+=str(""" written""")
		self.pylToHtmlResult+=str(""" on""")
		self.pylToHtmlResult+=str(""" the""")
		self.pylToHtmlResult+=str(""" code""")
		self.pylToHtmlResult+=str(""" specifically""")
		self.pylToHtmlResult+=str(""" before""")
		self.pylToHtmlResult+=str(""" using""")
		self.pylToHtmlResult+=str(""" database.""")
		self.pylToHtmlResult+=str(""" 
				<p>""")
		self.pylToHtmlResult+=str("""In""")
		self.pylToHtmlResult+=str(""" this""")
		self.pylToHtmlResult+=str(""" case,""")
		self.pylToHtmlResult+=str(""" DBMappingParser""")
		self.pylToHtmlResult+=str(""" class""")
		self.pylToHtmlResult+=str(""" and""")
		self.pylToHtmlResult+=str(""" db_mapping.xml""")
		self.pylToHtmlResult+=str(""" file""")
		self.pylToHtmlResult+=str(""" are""")
		self.pylToHtmlResult+=str(""" required""")
		self.pylToHtmlResult+=str(""" to""")
		self.pylToHtmlResult+=str(""" use.""")
		self.pylToHtmlResult+=str(""" Refer""")
		self.pylToHtmlResult+=str(""" to""")
		self.pylToHtmlResult+=str(""" following""")
		self.pylToHtmlResult+=str(""" code.""")
		self.pylToHtmlResult+=str("""</p>""")
		self.pylToHtmlResult+=str("""
				<pre class="brush: xml">""")
		self.pylToHtmlResult+=str("""
					<sqlMap id="user">""")
		self.pylToHtmlResult+=str("""
						<select id="select1">""")
		self.pylToHtmlResult+=str("""SELECT""")
		self.pylToHtmlResult+=str(""" *""")
		self.pylToHtmlResult+=str(""" FROM""")
		self.pylToHtmlResult+=str(""" table""")
		self.pylToHtmlResult+=str("""</select>""")
		self.pylToHtmlResult+=str("""
						<select id="select2">""")
		self.pylToHtmlResult+=str("""SELECT""")
		self.pylToHtmlResult+=str(""" *""")
		self.pylToHtmlResult+=str(""" FROM""")
		self.pylToHtmlResult+=str(""" table""")
		self.pylToHtmlResult+=str(""" WHERE""")
		self.pylToHtmlResult+=str(""" age""")
		self.pylToHtmlResult+=str(""" =""")
		self.pylToHtmlResult+=str(""" $age$""")
		self.pylToHtmlResult+=str("""</select>""")
		self.pylToHtmlResult+=str("""
						<insert id="insert1">""")
		self.pylToHtmlResult+=str("""INSERT""")
		self.pylToHtmlResult+=str(""" INTO""")
		self.pylToHtmlResult+=str(""" table""")
		self.pylToHtmlResult+=str(""" VALUES""")
		self.pylToHtmlResult+=str(""" ($name$,""")
		self.pylToHtmlResult+=str(""" $age$)""")
		self.pylToHtmlResult+=str("""</insert>""")
		self.pylToHtmlResult+=str("""
						<update id="update1">""")
		self.pylToHtmlResult+=str("""UPDATE""")
		self.pylToHtmlResult+=str(""" table""")
		self.pylToHtmlResult+=str(""" SET""")
		self.pylToHtmlResult+=str(""" age""")
		self.pylToHtmlResult+=str(""" =""")
		self.pylToHtmlResult+=str(""" $age$""")
		self.pylToHtmlResult+=str(""" WHERE""")
		self.pylToHtmlResult+=str(""" name""")
		self.pylToHtmlResult+=str(""" =""")
		self.pylToHtmlResult+=str(""" $name$""")
		self.pylToHtmlResult+=str("""</update>""")
		self.pylToHtmlResult+=str("""
						<delete id="delete1">""")
		self.pylToHtmlResult+=str("""DELETE""")
		self.pylToHtmlResult+=str(""" FROM""")
		self.pylToHtmlResult+=str(""" table""")
		self.pylToHtmlResult+=str(""" WHERE""")
		self.pylToHtmlResult+=str(""" age""")
		self.pylToHtmlResult+=str(""" =""")
		self.pylToHtmlResult+=str(""" $age$""")
		self.pylToHtmlResult+=str("""</delete>""")
		self.pylToHtmlResult+=str("""
					</sqlMap>""")
		self.pylToHtmlResult+=str("""
				</pre>""")
		self.pylToHtmlResult+=str("""
				<p>""")
		self.pylToHtmlResult+=str("""This""")
		self.pylToHtmlResult+=str(""" is""")
		self.pylToHtmlResult+=str(""" xml""")
		self.pylToHtmlResult+=str(""" code""")
		self.pylToHtmlResult+=str(""" in""")
		self.pylToHtmlResult+=str(""" <i>""")
		self.pylToHtmlResult+=str("""db_mapping.xml""")
		self.pylToHtmlResult+=str(""" file""")
		self.pylToHtmlResult+=str("""</i>""")
		self.pylToHtmlResult+=str(""".""")
		self.pylToHtmlResult+=str(""" &lt;sqlMap&gt;""")
		self.pylToHtmlResult+=str(""" tag""")
		self.pylToHtmlResult+=str(""" needs""")
		self.pylToHtmlResult+=str(""" attribute""")
		self.pylToHtmlResult+=str(""" 'id'.""")
		self.pylToHtmlResult+=str(""" And""")
		self.pylToHtmlResult+=str(""" its""")
		self.pylToHtmlResult+=str(""" child""")
		self.pylToHtmlResult+=str(""" nodes""")
		self.pylToHtmlResult+=str(""" (e.g.""")
		self.pylToHtmlResult+=str(""" select,""")
		self.pylToHtmlResult+=str(""" insert,""")
		self.pylToHtmlResult+=str(""" update,""")
		self.pylToHtmlResult+=str(""" delete""")
		self.pylToHtmlResult+=str(""" ...)""")
		self.pylToHtmlResult+=str(""" also""")
		self.pylToHtmlResult+=str(""" need""")
		self.pylToHtmlResult+=str(""" attribute""")
		self.pylToHtmlResult+=str(""" 'id'.""")
		self.pylToHtmlResult+=str(""" These""")
		self.pylToHtmlResult+=str(""" 'id'""")
		self.pylToHtmlResult+=str(""" are""")
		self.pylToHtmlResult+=str(""" used""")
		self.pylToHtmlResult+=str(""" to""")
		self.pylToHtmlResult+=str(""" call""")
		self.pylToHtmlResult+=str(""" SQL""")
		self.pylToHtmlResult+=str(""" which""")
		self.pylToHtmlResult+=str(""" is""")
		self.pylToHtmlResult+=str(""" values""")
		self.pylToHtmlResult+=str(""" of""")
		self.pylToHtmlResult+=str(""" the""")
		self.pylToHtmlResult+=str(""" childe""")
		self.pylToHtmlResult+=str(""" nodes.""")
		self.pylToHtmlResult+=str(""" Let's""")
		self.pylToHtmlResult+=str(""" see""")
		self.pylToHtmlResult+=str(""" how""")
		self.pylToHtmlResult+=str(""" to""")
		self.pylToHtmlResult+=str(""" deal""")
		self.pylToHtmlResult+=str(""" with""")
		self.pylToHtmlResult+=str(""" database""")
		self.pylToHtmlResult+=str(""" using""")
		self.pylToHtmlResult+=str(""" these""")
		self.pylToHtmlResult+=str(""" SQLs.""")
		self.pylToHtmlResult+=str("""</p>""")
		self.pylToHtmlResult+=str("""
				<pre class="brush: xml">""")
		self.pylToHtmlResult+=str("""
					<@latteDatabaseExt>""")
		self.pylToHtmlResult+=str("""
					&lt;$""")
		self.pylToHtmlResult+=str("""
					db""")
		self.pylToHtmlResult+=str(""" =""")
		self.pylToHtmlResult+=str(""" DBMappingParser.pyLatteDBMappingParser()""")
		self.pylToHtmlResult+=str("""
					parameter""")
		self.pylToHtmlResult+=str(""" =""")
		self.pylToHtmlResult+=str(""" {&quot;age&quot;:1,""")
		self.pylToHtmlResult+=str(""" &quot;name&quot;:&quot;pylatte&quot;}""")
		self.pylToHtmlResult+=str("""
					
					result1""")
		self.pylToHtmlResult+=str(""" =""")
		self.pylToHtmlResult+=str(""" db.queryForList(&quot;user.select1&quot;)""")
		self.pylToHtmlResult+=str("""
					result2""")
		self.pylToHtmlResult+=str(""" =""")
		self.pylToHtmlResult+=str(""" db.queryForList(&quot;user.select2&quot;,""")
		self.pylToHtmlResult+=str(""" parameter)""")
		self.pylToHtmlResult+=str("""
					$&gt;""")
		self.pylToHtmlResult+=str("""
				</pre>""")
		self.pylToHtmlResult+=str("""
				<p>""")
		self.pylToHtmlResult+=str("""First""")
		self.pylToHtmlResult+=str(""" of""")
		self.pylToHtmlResult+=str(""" all,""")
		self.pylToHtmlResult+=str(""" declare""")
		self.pylToHtmlResult+=str(""" on""")
		self.pylToHtmlResult+=str(""" variable""")
		self.pylToHtmlResult+=str(""" and""")
		self.pylToHtmlResult+=str(""" call""")
		self.pylToHtmlResult+=str(""" DBMappingParser.pyLatteDBMappingParser()""")
		self.pylToHtmlResult+=str(""" to""")
		self.pylToHtmlResult+=str(""" save""")
		self.pylToHtmlResult+=str(""" database""")
		self.pylToHtmlResult+=str(""" object""")
		self.pylToHtmlResult+=str(""" to""")
		self.pylToHtmlResult+=str(""" the""")
		self.pylToHtmlResult+=str(""" variable.""")
		self.pylToHtmlResult+=str("""</p>""")
		self.pylToHtmlResult+=str("""
				<p>""")
		self.pylToHtmlResult+=str("""Secondly,""")
		self.pylToHtmlResult+=str(""" define""")
		self.pylToHtmlResult+=str(""" dictionary""")
		self.pylToHtmlResult+=str(""" type""")
		self.pylToHtmlResult+=str(""" parameter.""")
		self.pylToHtmlResult+=str(""" This""")
		self.pylToHtmlResult+=str(""" will""")
		self.pylToHtmlResult+=str(""" be""")
		self.pylToHtmlResult+=str(""" replaced""")
		self.pylToHtmlResult+=str(""" matched""")
		self.pylToHtmlResult+=str(""" value""")
		self.pylToHtmlResult+=str(""" in""")
		self.pylToHtmlResult+=str(""" SQL.""")
		self.pylToHtmlResult+=str("""</p>""")
		self.pylToHtmlResult+=str("""
				<p>""")
		self.pylToHtmlResult+=str("""At""")
		self.pylToHtmlResult+=str(""" last,""")
		self.pylToHtmlResult+=str(""" call""")
		self.pylToHtmlResult+=str(""" queryForList()""")
		self.pylToHtmlResult+=str(""" method""")
		self.pylToHtmlResult+=str(""" via""")
		self.pylToHtmlResult+=str(""" the""")
		self.pylToHtmlResult+=str(""" variable""")
		self.pylToHtmlResult+=str(""" declared""")
		self.pylToHtmlResult+=str(""" on""")
		self.pylToHtmlResult+=str(""" first""")
		self.pylToHtmlResult+=str(""" step.""")
		self.pylToHtmlResult+=str("""</p>""")
		self.pylToHtmlResult+=str("""
				<p>""")
		self.pylToHtmlResult+=str("""queryForList()""")
		self.pylToHtmlResult+=str(""" method""")
		self.pylToHtmlResult+=str(""" takes""")
		self.pylToHtmlResult+=str(""" two""")
		self.pylToHtmlResult+=str(""" parameters.""")
		self.pylToHtmlResult+=str("""</p>""")
		self.pylToHtmlResult+=str("""
				<p>""")
		self.pylToHtmlResult+=str("""First""")
		self.pylToHtmlResult+=str(""" one""")
		self.pylToHtmlResult+=str(""" indicates""")
		self.pylToHtmlResult+=str(""" specific""")
		self.pylToHtmlResult+=str(""" SQL""")
		self.pylToHtmlResult+=str(""" in""")
		self.pylToHtmlResult+=str(""" db_mapping.xml""")
		self.pylToHtmlResult+=str(""" by""")
		self.pylToHtmlResult+=str(""" id.""")
		self.pylToHtmlResult+=str(""" For""")
		self.pylToHtmlResult+=str(""" example,""")
		self.pylToHtmlResult+=str(""" 'user.select1'""")
		self.pylToHtmlResult+=str(""" indicates""")
		self.pylToHtmlResult+=str(""" a""")
		self.pylToHtmlResult+=str(""" value""")
		self.pylToHtmlResult+=str(""" in""")
		self.pylToHtmlResult+=str(""" specific""")
		self.pylToHtmlResult+=str(""" tag""")
		self.pylToHtmlResult+=str(""" which""")
		self.pylToHtmlResult+=str(""" has""")
		self.pylToHtmlResult+=str(""" id""")
		self.pylToHtmlResult+=str(""" 'select1'""")
		self.pylToHtmlResult+=str(""" in""")
		self.pylToHtmlResult+=str(""" &lt;sqlMap&gt;""")
		self.pylToHtmlResult+=str(""" tag""")
		self.pylToHtmlResult+=str(""" having""")
		self.pylToHtmlResult+=str(""" id""")
		self.pylToHtmlResult+=str(""" 'user'.""")
		self.pylToHtmlResult+=str(""" So""")
		self.pylToHtmlResult+=str(""" 'user.select1'""")
		self.pylToHtmlResult+=str(""" get""")
		self.pylToHtmlResult+=str(""" replaced""")
		self.pylToHtmlResult+=str(""" to""")
		self.pylToHtmlResult+=str(""" &quot;SELECT""")
		self.pylToHtmlResult+=str(""" *""")
		self.pylToHtmlResult+=str(""" FROM""")
		self.pylToHtmlResult+=str(""" test&quot;""")
		self.pylToHtmlResult+=str("""</p>""")
		self.pylToHtmlResult+=str("""
				<p>""")
		self.pylToHtmlResult+=str("""Second""")
		self.pylToHtmlResult+=str(""" parameter""")
		self.pylToHtmlResult+=str(""" is""")
		self.pylToHtmlResult+=str(""" optional.""")
		self.pylToHtmlResult+=str(""" When""")
		self.pylToHtmlResult+=str(""" SQL""")
		self.pylToHtmlResult+=str(""" indicated""")
		self.pylToHtmlResult+=str(""" by""")
		self.pylToHtmlResult+=str(""" first""")
		self.pylToHtmlResult+=str(""" parameter""")
		self.pylToHtmlResult+=str(""" includes""")
		self.pylToHtmlResult+=str(""" variable""")
		self.pylToHtmlResult+=str(""" $keys$,""")
		self.pylToHtmlResult+=str(""" this""")
		self.pylToHtmlResult+=str(""" is""")
		self.pylToHtmlResult+=str(""" mandatory.""")
		self.pylToHtmlResult+=str(""" As""")
		self.pylToHtmlResult+=str(""" you""")
		self.pylToHtmlResult+=str(""" see""")
		self.pylToHtmlResult+=str(""" above""")
		self.pylToHtmlResult+=str(""" example""")
		self.pylToHtmlResult+=str(""" code,""")
		self.pylToHtmlResult+=str(""" second""")
		self.pylToHtmlResult+=str(""" parameter""")
		self.pylToHtmlResult+=str(""" is""")
		self.pylToHtmlResult+=str(""" dictionary""")
		self.pylToHtmlResult+=str(""" type.""")
		self.pylToHtmlResult+=str(""" In""")
		self.pylToHtmlResult+=str(""" the""")
		self.pylToHtmlResult+=str(""" parameter,""")
		self.pylToHtmlResult+=str(""" the""")
		self.pylToHtmlResult+=str(""" each""")
		self.pylToHtmlResult+=str(""" values""")
		self.pylToHtmlResult+=str(""" automatically""")
		self.pylToHtmlResult+=str(""" gets""")
		self.pylToHtmlResult+=str(""" replaced""")
		self.pylToHtmlResult+=str(""" with""")
		self.pylToHtmlResult+=str(""" each""")
		self.pylToHtmlResult+=str(""" matched""")
		self.pylToHtmlResult+=str(""" $keys$""")
		self.pylToHtmlResult+=str(""" in""")
		self.pylToHtmlResult+=str(""" SQL.""")
		self.pylToHtmlResult+=str(""" So""")
		self.pylToHtmlResult+=str(""" select2""")
		self.pylToHtmlResult+=str(""" will""")
		self.pylToHtmlResult+=str(""" be""")
		self.pylToHtmlResult+=str(""" traslated""")
		self.pylToHtmlResult+=str(""" from""")
		self.pylToHtmlResult+=str(""" <b>""")
		self.pylToHtmlResult+=str("""SELECT""")
		self.pylToHtmlResult+=str(""" *""")
		self.pylToHtmlResult+=str(""" FROM""")
		self.pylToHtmlResult+=str(""" test""")
		self.pylToHtmlResult+=str(""" WHERE""")
		self.pylToHtmlResult+=str(""" age""")
		self.pylToHtmlResult+=str(""" =""")
		self.pylToHtmlResult+=str(""" $age$""")
		self.pylToHtmlResult+=str("""</b>""")
		self.pylToHtmlResult+=str(""" to""")
		self.pylToHtmlResult+=str(""" <b>""")
		self.pylToHtmlResult+=str("""SELECT""")
		self.pylToHtmlResult+=str(""" *""")
		self.pylToHtmlResult+=str(""" FROM""")
		self.pylToHtmlResult+=str(""" test""")
		self.pylToHtmlResult+=str(""" WHERE""")
		self.pylToHtmlResult+=str(""" age""")
		self.pylToHtmlResult+=str(""" =""")
		self.pylToHtmlResult+=str(""" 1""")
		self.pylToHtmlResult+=str("""</b>""")
		self.pylToHtmlResult+=str("""</p>""")
		self.pylToHtmlResult+=str("""
				<p>""")
		self.pylToHtmlResult+=str("""queryForList()""")
		self.pylToHtmlResult+=str(""" method""")
		self.pylToHtmlResult+=str(""" returns""")
		self.pylToHtmlResult+=str(""" tuple""")
		self.pylToHtmlResult+=str(""" type""")
		self.pylToHtmlResult+=str(""" as""")
		self.pylToHtmlResult+=str(""" a""")
		self.pylToHtmlResult+=str(""" result.""")
		self.pylToHtmlResult+=str("""</p>""")
		self.pylToHtmlResult+=str("""
				
							
			<h2>""")
		self.pylToHtmlResult+=str("""Server""")
		self.pylToHtmlResult+=str(""" Information""")
		self.pylToHtmlResult+=str("""</h2>""")
		self.pylToHtmlResult+=str("""
				<p>""")
		self.pylToHtmlResult+=str("""It""")
		self.pylToHtmlResult+=str(""" is""")
		self.pylToHtmlResult+=str(""" possible""")
		self.pylToHtmlResult+=str(""" to""")
		self.pylToHtmlResult+=str(""" get""")
		self.pylToHtmlResult+=str(""" HTTP""")
		self.pylToHtmlResult+=str(""" header""")
		self.pylToHtmlResult+=str(""" information""")
		self.pylToHtmlResult+=str(""" that""")
		self.pylToHtmlResult+=str(""" you""")
		self.pylToHtmlResult+=str(""" required""")
		self.pylToHtmlResult+=str(""" to""")
		self.pylToHtmlResult+=str(""" Pylatte""")
		self.pylToHtmlResult+=str(""" web""")
		self.pylToHtmlResult+=str(""" server.""")
		self.pylToHtmlResult+=str(""" It""")
		self.pylToHtmlResult+=str(""" is""")
		self.pylToHtmlResult+=str(""" also""")
		self.pylToHtmlResult+=str(""" saved""")
		self.pylToHtmlResult+=str(""" as""")
		self.pylToHtmlResult+=str(""" dictionary""")
		self.pylToHtmlResult+=str(""" type.""")
		self.pylToHtmlResult+=str(""" Refer""")
		self.pylToHtmlResult+=str(""" to""")
		self.pylToHtmlResult+=str(""" following""")
		self.pylToHtmlResult+=str(""" code""")
		self.pylToHtmlResult+=str(""" to""")
		self.pylToHtmlResult+=str(""" see""")
		self.pylToHtmlResult+=str(""" how""")
		self.pylToHtmlResult+=str(""" to""")
		self.pylToHtmlResult+=str(""" use""")
		self.pylToHtmlResult+=str(""" it""")
		self.pylToHtmlResult+=str(""" in""")
		self.pylToHtmlResult+=str(""" pyl.""")
		self.pylToHtmlResult+=str("""</p>""")
		self.pylToHtmlResult+=str("""
				<pre class="brush: xml">""")
		self.pylToHtmlResult+=str("""
					&lt;$=headerInfo["User-Agent"]$&gt;""")
		self.pylToHtmlResult+=str("""
					&lt;$=headerInfo["Accept-Encoding"]$&gt;""")
		self.pylToHtmlResult+=str("""
				</pre>""")
		self.pylToHtmlResult+=str("""
				<p>""")
		self.pylToHtmlResult+=str("""There""")
		self.pylToHtmlResult+=str(""" are""")
		self.pylToHtmlResult+=str(""" planty""")
		self.pylToHtmlResult+=str(""" of""")
		self.pylToHtmlResult+=str(""" header""")
		self.pylToHtmlResult+=str(""" information.""")
		self.pylToHtmlResult+=str(""" Pylatte""")
		self.pylToHtmlResult+=str(""" support""")
		self.pylToHtmlResult+=str(""" most""")
		self.pylToHtmlResult+=str(""" common""")
		self.pylToHtmlResult+=str(""" header""")
		self.pylToHtmlResult+=str(""" information.""")
		self.pylToHtmlResult+=str("""</p>""")
		self.pylToHtmlResult+=str("""
			</div>""")
		self.pylToHtmlResult+=str("""<!--/content-primary -->""")
		self.pylToHtmlResult+=str("""

			<div class="content-secondary">""")
		self.pylToHtmlResult+=str("""

				<div data-role="collapsible" data-collapsed="true" data-theme="b" data-content-theme="d">""")
		self.pylToHtmlResult+=str("""

						<h3>""")
		self.pylToHtmlResult+=str("""More""")
		self.pylToHtmlResult+=str(""" in""")
		self.pylToHtmlResult+=str(""" this""")
		self.pylToHtmlResult+=str(""" section""")
		self.pylToHtmlResult+=str("""</h3>""")
		self.pylToHtmlResult+=str("""

						<ul data-role="listview" data-theme="c" data-dividertheme="d">""")
		self.pylToHtmlResult+=str("""
							<li data-role="list-divider">""")
		self.pylToHtmlResult+=str("""Menu""")
		self.pylToHtmlResult+=str("""</li>""")
		self.pylToHtmlResult+=str("""
							<li>""")
		self.pylToHtmlResult+=str("""<a target="_self" href="../index">""")
		self.pylToHtmlResult+=str("""About""")
		self.pylToHtmlResult+=str("""</a>""")
		self.pylToHtmlResult+=str("""</li>""")
		self.pylToHtmlResult+=str("""
							<li>""")
		self.pylToHtmlResult+=str("""<a target="_self" href="../download">""")
		self.pylToHtmlResult+=str("""Download""")
		self.pylToHtmlResult+=str("""</a>""")
		self.pylToHtmlResult+=str("""</li>""")
		self.pylToHtmlResult+=str("""
							<li>""")
		self.pylToHtmlResult+=str("""<a target="_self" href="../install">""")
		self.pylToHtmlResult+=str("""Install""")
		self.pylToHtmlResult+=str("""</a>""")
		self.pylToHtmlResult+=str("""</li>""")
		self.pylToHtmlResult+=str("""
							<li data-theme="b">""")
		self.pylToHtmlResult+=str("""<a target="_self" href="../tutorial">""")
		self.pylToHtmlResult+=str("""Tutorial""")
		self.pylToHtmlResult+=str("""</a>""")
		self.pylToHtmlResult+=str("""</li>""")
		self.pylToHtmlResult+=str("""
							<li>""")
		self.pylToHtmlResult+=str("""<a target="_self" href="../documentation">""")
		self.pylToHtmlResult+=str("""Documentation""")
		self.pylToHtmlResult+=str("""</a>""")
		self.pylToHtmlResult+=str("""</li>""")
		self.pylToHtmlResult+=str("""
							<li>""")
		self.pylToHtmlResult+=str("""<a target="_self" href="../faq">""")
		self.pylToHtmlResult+=str("""F""")
		self.pylToHtmlResult+=str(""" A""")
		self.pylToHtmlResult+=str(""" Q""")
		self.pylToHtmlResult+=str("""</a>""")
		self.pylToHtmlResult+=str("""</li>""")
		self.pylToHtmlResult+=str("""
							<li>""")
		self.pylToHtmlResult+=str("""<a target="_self" href="../contactus">""")
		self.pylToHtmlResult+=str("""Contact""")
		self.pylToHtmlResult+=str(""" us""")
		self.pylToHtmlResult+=str("""</a>""")
		self.pylToHtmlResult+=str("""</li>""")
		self.pylToHtmlResult+=str("""
							<li>""")
		self.pylToHtmlResult+=str("""<a target="_self" href="../demo1">""")
		self.pylToHtmlResult+=str("""Demo1""")
		self.pylToHtmlResult+=str("""</a>""")
		self.pylToHtmlResult+=str("""</li>""")
		self.pylToHtmlResult+=str("""
							<li>""")
		self.pylToHtmlResult+=str("""<a target="_self" href="../demo2">""")
		self.pylToHtmlResult+=str("""Demo2""")
		self.pylToHtmlResult+=str("""</a>""")
		self.pylToHtmlResult+=str("""</li>""")
		self.pylToHtmlResult+=str("""
							<li>""")
		self.pylToHtmlResult+=str("""<a target="_self" href="../demo3">""")
		self.pylToHtmlResult+=str("""Demo3""")
		self.pylToHtmlResult+=str("""</a>""")
		self.pylToHtmlResult+=str("""</li>""")
		self.pylToHtmlResult+=str("""
							<img src="../pyl/image/pylatte.png">""")
		self.pylToHtmlResult+=str("""</img>""")
		self.pylToHtmlResult+=str("""
						</ul>""")
		self.pylToHtmlResult+=str("""
				</div>""")
		self.pylToHtmlResult+=str("""
			</div>""")
		self.pylToHtmlResult+=str("""

		</div>""")
		self.pylToHtmlResult+=str("""<!-- /content -->""")
		self.pylToHtmlResult+=str("""

		<div data-role="footer" class="footer-docs" data-theme="b">""")
		self.pylToHtmlResult+=str("""
				<h4>""")
		self.pylToHtmlResult+=str("""&copy;""")
		self.pylToHtmlResult+=str(""" 2011""")
		self.pylToHtmlResult+=str(""" The""")
		self.pylToHtmlResult+=str(""" Pylatte""")
		self.pylToHtmlResult+=str(""" Project""")
		self.pylToHtmlResult+=str("""</h4>""")
		self.pylToHtmlResult+=str("""
		</div>""")
		self.pylToHtmlResult+=str("""

		</div>""")
		self.pylToHtmlResult+=str("""<!-- /page -->""")
		self.pylToHtmlResult+=str("""
	
		</body>""")
		self.pylToHtmlResult+=str("""
	<!-- Finally, to actually run the highlighter, you need to include this JS on your page -->""")
		self.pylToHtmlResult+=str("""
	<script type="text/javascript">""")
		self.pylToHtmlResult+=str("""
		SyntaxHighlighter.all()""")
		self.pylToHtmlResult+=str("""
	</script>""")
		self.pylToHtmlResult+=str("""
</html>""")
		self.sessionDic=session
		pass
	def getHtml(self):
		return self.pylToHtmlResult
		pass
	def getSession(self):
		return self.sessionDic
		pass
